### ISSUE TITLE
Issue while restoring Design Docs in Couchbase (4.6.0-3453 Enterprise Edition).

### ISSUE THREAD

**Issue by arunravimv** [dmsl/anyplace#103]
>Couchbase Version : 4.6.0-3453 Enterprise Edition (build-3453)

The path to view file is :

> /home/couchsrv/anyplacedata/bucket-anyplace/desgin.json
I had renamed the file ddocs.json to design.json

`cbrestore /home/couchsrv/anyplacedata http://anyplace:admin@localhost:8091 -x design_doc_only=1 -b anyplace -B anyplace`

The response of the above command.
> transfer design doc only. bucket msgs will be skipped.
> done

I guess my import is incomplete.
I am getting following Error in the server code.

>Cannot invoke the action, eventually got an error: com.couchbase.client.protocol.views.InvalidViewException: Could not load view "building_all" for design doc "nav"

**Comment by dynougX** [comment]
hi, arunravimv. I got the same issue. Have you solved it? Could you share your solution?

**Comment by dynougX** [comment]
@anyplaceucy @kgeorgiou

**Comment by arunravimv** [comment]
@dynougX yes, use this latest structure to create views for development and then you can publish it to production.
[anyplaceViews.zip](https://github.com/dmsl/anyplace/files/803525/anyplaceViews.zip)

Use the following curl command to import it to development.
`curl -X PUT -H "Content-Type: application/json"  http://username:password@host:port/bucket/_design/dev_accounts -d @accounts.json`

**Comment by anyplaceucy** [comment]
There is an official patch for the latest Couchbase rolling out soon. Please stay tuned.

**Comment by Fullg0lden** [comment]
@anyplaceucy When will your server compatible with couchbase 3.x be released? Thanks.

**Comment by anyplaceucy** [comment]
It has been released. For more check the github page: https://github.com/dmsl/anyplace
