### ISSUE TITLE
Setting up the AnyPlace platform and Android app

### ISSUE THREAD

**Issue by ilangolulu** [dmsl/anyplace#104]
I am just getting started trying to understand the idea of Indoor Maps Navigation. I know a few things by now, for example, I know these applications are built on top of Google Maps.
That said, I think this software is just the right place for me to to get started.
First, how do I set up your platform?
So far from what I have read there is a Play application with a Couchbase database. Is this the backend of the AnyPlace application?  I only have local computer to set this up. (this is what I  have interpreted so far)
The Android app, which I can set up in Android Studio will access the backend running on my local computer?
Please help me understand this more.

**Comment by anyplaceucy** [comment]
You can read this: http://www.cs.ucy.ac.cy/~dzeina/papers/mdm15-anyplace-demo.pdf

**Comment by anyplaceucy** [comment]
This is also useful and provides a more general perspective on the area:

http://www.cs.ucy.ac.cy/~dzeina/papers/ic16-iin.pdf

A powerpoint presentation accompanying the above is available at the below URL:

https://dmsl.cs.ucy.ac.cy/tutorials/mdm15/


The Anyplace Team
