### ISSUE TITLE
Failed to install Architect

### ISSUE THREAD

**Issue by mmounirf** [dmsl/anyplace#105]
Hello,
I did follow up the following video
https://www.youtube.com/watch?v=m7uFkm2xHEU

However, it seems that the errors shown in the video is not what I have in here. My machine running with the following:-
1- Node v6.9.5
2- npm v3.10.10
3- bower  v1.8.0

![screenshot](https://cloud.githubusercontent.com/assets/5405713/23091863/3ce827e4-f5c8-11e6-837b-31ff00912de2.png)

**Comment by EchoYangYG** [comment]
I also has this problem, does anyone know how to solve it?

**Comment by EchoYangYG** [comment]
Hi, I think I may found the way to solve, you may refer to issue #106 to see weather it can work

**Comment by mmounirf** [comment]
Hi,
Thank you @EchoYangYG and sorry for the late feedback. I re-installed using the AngularJS you specified in issue #106 and it seems that it clears most of console error, however I'm still struggling retrieving data (fetching building) or add new building. Returned data is undefined.

![untitled](https://cloud.githubusercontent.com/assets/5405713/23254152/b7ae075a-f9bf-11e6-8243-b53662ebd0a7.png)

**Comment by anushatamanampudi** [comment]
Were u able to resolve this ?

**Comment by mmounirf** [comment]
@anushatamanampudi unfortunately no

**Comment by anyplaceucy** [comment]
Fixed in Anyplace v3. For more check the github page: https://github.com/dmsl/anyplace
