### ISSUE TITLE
cannot add new building

### ISSUE THREAD

**Issue by EchoYangYG** [dmsl/anyplace#106]
hello, I just set up the project on my PC , however, when i try to add new building, it throws the error as following pic, does anyone know why and how to do?
![anyplace-issue](https://cloud.githubusercontent.com/assets/25890529/23113361/9415167a-f772-11e6-988a-d23df12ef8ac.jpg)
Thank you!

**Comment by EchoYangYG** [comment]
@anyplaceucy Is this project still maintenance? Can you help me? The installation for viewer has almost same problem

**Comment by anyplaceucy** [comment]
We rely on community engagement with problem debugging & solving issues. Its good if users with experience on installation / configuration give back to fellow users.

**Comment by EchoYangYG** [comment]
I found out the issue!  in Angular 1.6 the $http Success/Error callback methods have been deprecated.
They should be replaced by .then(...) everywhere in this library. So I use angular 1.3.20 and it can work now!

**Comment by anyplaceucy** [comment]
Would you kindly push this fix under https://github.com/dmsl/anyplace/tree/develop for integration in future releases.

Thanks,
Anyplace Team
