### ISSUE TITLE
request for old version couchbase server or new version design documents

### ISSUE THREAD

**Issue by dynougX** [dmsl/anyplace#107]
could you please provide a link for downloading 2.2.1 community version? The official website is no longer provide. Or could you provide new design document which could run on couchbase 3.0 or higher?

**Comment by dynougX** [comment]
@anyplaceucy @kgeorgiou

**Comment by anyplaceucy** [comment]
In progress

**Comment by kgeorgiou** [comment]
You can build version 2.2.1 as described in the README file under Couchbase's [repository](https://github.com/couchbase/manifest). There's another resource that might be helpful available [here](https://www.digitalocean.com/community/tutorials/how-to-install-couchbase-from-source-with-git-and-make-on-a-debian-7-vps).

I haven't tested this yet, I'll update once I do.

**Comment by anyplaceucy** [comment]
Fixed in Anyplace v3. For more check the github page: https://github.com/dmsl/anyplace
