### ISSUE TITLE
Using Anyplace in my Local Server

### ISSUE THREAD

**Issue by ourdex86** [dmsl/anyplace#108]
Hi,

I want to use this anyplace project for one of my internal project and I want to use the local server URL for the android application.

How can I achieve this ?

**Comment by anyplaceucy** [comment]
Check https://github.com/dmsl/anyplace/tree/master/server

**Comment by ourdex86** [comment]
Hi,

I saw this. But, how can I change the url inside the Android app to my
server address ??

**Comment by constambeys** [comment]
Change the server variable in com.dmsl.anyplace.AnyplaceAPI class
