### ISSUE TITLE
Anyplace API

### ISSUE THREAD

**Issue by elmustaphah** [dmsl/anyplace#109]
Hello,

I am developing an prototype for a navigation project in my university building, I am not exactly sure whether I should first add my building on the API or on the Architect. I am finding a bit hard to understand how to use the provided interface.

Would you be able to clarify what the API does and how it is different from the Architect?

**Comment by anyplaceucy** [comment]
Watch the videos at http://anyplace.cs.ucy.ac.cy/  

The API allows you to access the subroutines through your own program. For the time being, you might want to stick to the Architect and Viewer only. Particularly,

In beginner mode, use the Architect and Viewer only
In elementary mode, use the Logger/Navigator. 
In intermediate mode use the API 
In advanced mode, install the stack on your own hardware

The Anyplace Team

**Comment by elmustaphah** [comment]
I've installed the Anyplace App from play store, but when I try to navigate to a point, it always says that it unable or that there is no route from my location. I can clearly see my location in the map as I move, but cannot navigate, any clues why?

**Comment by constambeys** [comment]
Can you specify the target building/point and the starting position?

**Comment by elmustaphah** [comment]
@constambeys Thank you for your reply, I have managed to sort it out, but anyway the building is Newton Building this is the link: https://anyplace.cs.ucy.ac.cy/viewer/?buid=building_0aa5f662-b315-4f79-aa8b-356c4ca78c4c_1484486709562
