### ISSUE TITLE
Navigation on different devices

### ISSUE THREAD

**Issue by zuphilip** [dmsl/anyplace#11]
Do you have any reference device (vendor? model?), on which the navigation is working especially good? It seems for me that devices with a bad magnetic sensor or not working well in Anyplace navigation. Which sensors are influencing the navigation in Anyplace? I tried to find out about the sensors on my device with this app (and the result looked actually very similar):

<img src="https://lh5.ggpht.com/JvJ4KquR4buK1iRfxtn8bFOGwz81mQWdfiFzVIh6S_XYgg9SKIii1n9I73LZKCz6OZ0=h900" width="30%">

**Comment by constambeys** [comment]
We don't use the magnetic sensor directly in the application. Maybe is used by the system to provide the orientation of the user. In addition modern mobile phones support a step counter sensor which is better than the software implementation. Furthermore some phones have a higher WiFi scanning rate that make collecting the radiomaps easier.

**Comment by Derek-K** [comment]
I have tested on both Samsung device (Phone: Note2 7105 and Tablet: Tab 7 SM-T330)
This explains why both device failed to detect my direction of movement. It is always assume I was walking NORTH even I was walking SOUTH. It detects I was walking and my position always goes up (North) then after a while it snap back in place and repeats.

May I ask the developers to fix this? Perhaps make use of the magnetic sensor?

I just can't never get it work as smooth as the demo video. :(

**Comment by constambeys** [comment]
You can check that the orientation is working by viewing the logger heading number at the textbox below the map. This number should change quickly according to the device heading

**Comment by Derek-K** [comment]
Yea, on both device always shows 0'....

**Comment by constambeys** [comment]
What android version are you running? Is it stock or rooted?
