### ISSUE TITLE
Unable to navigate

### ISSUE THREAD

**Issue by elmustaphah** [dmsl/anyplace#110]
I've installed the Anyplace App from play store, but when I try to navigate to a point, it always says that it unable or that there is no route from my location. I can clearly see my location in the map as I move, but cannot navigate, any clues why?

**Comment by anyplaceucy** [comment]
Have you mapped your building on Architect (https://anyplace.cs.ucy.ac.cy/architect/) ? You need to add the POIs, connectors, and denote at least 1 POI as a "building entrance" to obtain navigation instructions. See the video: https://youtu.be/dIVxcQ_5Wbg
