### ISSUE TITLE
Wrong position of map

### ISSUE THREAD

**Issue by elmustaphah** [dmsl/anyplace#111]
I'm trying to add second floor: https://anyplace.cs.ucy.ac.cy/viewer/?buid=building_0aa5f662-b315-4f79-aa8b-356c4ca78c4c_1484486709562
But when I try to view it on the navigator this is what I get:
![img_7177](https://cloud.githubusercontent.com/assets/25204069/23651392/510fad48-031d-11e7-93d9-3fd656f470bd.JPG)
What could be the reason?

**Comment by anyplaceucy** [comment]
You should connect floor levels with edges (lines). Particularly, connect elevators or stairs. Also remember that every building needs at least 1 entrance. In this way you will get outdoor-to-indoor navigation to the closest building entrance to your POI of interest.
