### ISSUE TITLE
Misplaced floor plan on Navigator app

### ISSUE THREAD

**Issue by EmrahKK** [dmsl/anyplace#112]
Floor plan that I've prepared on the architect app shows up in different position in Navigator app. I cannot manage to fix the position as proposed by zooming max level on the map. How can fix this?

**Comment by anyplaceucy** [comment]
Break the picture into multiple buildings or open architect on a screen that supports a higher resolution (pixels) than your current screen.

**Comment by EmrahKK** [comment]
İf I break the floor picture into multiple buildings then how can I use logger to collect rss logs. I don't understand. There will be multiple buildings...

**Comment by anyplaceucy** [comment]
You will collect separate measurements per building. After the buildings are mapped, the navigator will automatically change from the one building to the next one as you move on (by proximity).

**Comment by anyplaceucy** [comment]
That's actually also better from a performance stand-point (having huge buildings will result in more network traffic)

**Comment by EmrahKK** [comment]
Well, after many unsuccessful attempts I figure it out. When you zoom to the lowest level on the architect and place the floor plan image, it doesn't show up on the correct place in the Android mobile app. Bu if you use 2. lowest level it places it correctly!
