### ISSUE TITLE
How do i access non-public buildings through api in Android app?

### ISSUE THREAD

**Issue by abvyascygnet** [dmsl/anyplace#115]
I have created some building as non-public building. But when i am trying to access it through android app, i am not able to do that. Can you please help me to come out of it?

**Comment by constambeys** [comment]
Can you sent your building id to my email timo0190@gmail.com.

**Comment by constambeys** [comment]
Hello abvyascygnet

I have tested the building id and it works. The private building is added by opening select building and then clicking the settings key or the back button continuously. Click add building and type the building id.

**Comment by abvyascygnet** [comment]
Thank you so much constambeys !!
