### ISSUE TITLE
Floor to floor navigation

### ISSUE THREAD

**Issue by spiral360** [dmsl/anyplace#118]
Im trying to navigate from the ground floor to 1st floor of a building can that be done using connectors or do i have to log the path?

**Comment by kgeorgiou** [comment]
Hello @spiral360. For floor to floor navigation, POIs with type `elevator` and `stair` are used to connect floors. 

With that said, all that's needed is for the target POI to be connected to an `elevator` or `stair` type of POI. You can see a example of navigating from floor -1 to floor 2 in the Anyplace Navigator [video](https://www.youtube.com/watch?v=MO-473oWSfE). 

The connections from POI to POI are set up through [Anyplace Architect](https://anyplace.cs.ucy.ac.cy/architect), by users that have access to the floor in discussion. 

So the short answer to the question is that it can be done using connectors.

**Comment by spiral360** [comment]
thanks
