### ISSUE TITLE
BLE Beancons

### ISSUE THREAD

**Issue by enyachoke** [dmsl/anyplace#12]
Just out of curiosity why did you choose to use wifi instead of beacons I understand that in some places already exists wifi infrastructure but what of a place where the is no wifi. I believe it may be cheaper to setup a beacon infrastructure in this case. Any reasons against using beacons and how easy is it to convert this to use beacons.

**Comment by dzeina** [comment]
Beacons are under the general category of "infrastructure"-based solutions while Anyplace is an infrastructure-free solution (check this recent article for more info: http://www.cs.ucy.ac.cy/~dzeina/papers/ic16-iin.pdf).

Nevertheless, we already look the integration of beacons into Anyplace (as a non-core feature), but progress on this will take more time unless we have the community to back this. A good starting point is the Hitchhikers Guide to iBeacon Hardware (http://www.aislelabs.com/reports/beacon-guide/).

Demetris

**Comment by dzeina** [comment]
Using beacons with Anyplace boils down to the following logic:

a) You map a building using Anyplace "Architect".
b) You collect the Radiomap using Anyplace "Logger" (Android) - Now you have the WiFi map - observe your progress on Architect. This now provides room-level localization accuracy (1-2 meters at best).
c) You modify "Viewer" (All platforms) or "Navigator" (Android/Windows) to integrate the beacons of your choice (e.g., show them on the Viewer map). You can also tweak localization, such that it occurs both through beacons (fine accuracy) and Anyplace (room-level accuracy).
d) To select the right type of beacon technology refer to Aislelab's guide (http://www.aislelabs.com/reports/beacon-guide/).

Demetris

**Comment by enyachoke** [comment]
@dzeina  Can you use a ble radiomap instead of a wifi radiomap. With modification to the code that is.
