### ISSUE TITLE
I have installed my own local server and everything works properly incluging sign in,viewer etc. But when i am trying to add a new building although the data is being stored in my couchbase views the data is not retained. I also see the following errors. Can somebody help me on this.

### ISSUE THREAD

**Issue by anushatamanampudi** [dmsl/anyplace#120]
![image](https://cloud.githubusercontent.com/assets/13910610/24778315/bc240f9c-1ade-11e7-8a06-e05f5d67ae7e.png)

**Comment by kgeorgiou** [comment]
Hello @anushatamanampudi, have you managed to overcome this? 

You've installed the necessary packaged by running `npm install` and `bower install`, correct?

**Comment by anushatamanampudi** [comment]
Yes I was able to . Thank you
