### ISSUE TITLE
iPhone compatibility 

### ISSUE THREAD

**Issue by elmustaphah** [dmsl/anyplace#122]
Hello
I was wondering why Anyplace doesn't work on iPhone but works on Windows although most smartphone users are Android and iOS?

Regards

**Comment by anyplaceucy** [comment]
An iPhone version is work-in-progress: https://github.com/dmsl/anyplace/tree/master/ios. 

Given that iOS doesn't support Wi-Fi logging, the plan was to offer magnetic logging. Yet, we are still researching this area and should be posting an update in the future. It can be expected that the iOS version will be a implemented on top of the Ionic Framework (i.e., a natification of the AngularJS "Viewer" + a native magnetic library for localization. 

Anyplace Team

**Comment by fobus42** [comment]
First, thanks for this great job.
Is IOS still in development? Are there any progress?

**Comment by beattyr** [comment]
Has there been any update on the IOS version of this app?
