### ISSUE TITLE
How to use the app - Execute radio measurements

### ISSUE THREAD

**Issue by neofytos** [dmsl/anyplace#123]
I am not sure if i have understood how the app is working and how can i make radio measurements.

I have understood these:

1) By using ANYPLACE ARCHITECT we upload the top view of a building on the cloud and we match it at google maps. Also we insert the  POINTS OF INTEREST  and by using  connectors and edges we design the path that we will follow in the building. This procedure is not applied through our application on our smartphone, but by a computer using ANYPLACE ARCHITECT.

2) In the chosen building we execute radio measurements by using Logger and then we upload them to the cloud.

Please send to me feedback with steps of using the app.

For example:

1)Upload the top view with ANYPLACE ARCHITECT
2)Go to the building open the logger ....(description how to use it)..etc
3)Upload measurements  with...etc

Thank you.

**Comment by kgeorgiou** [comment]
Hello @neofytos,

### **Step 1:** Upload floor plan image(s) and add points of interest.

This process happens online at [Anyplace Architect](https://anyplace.cs.ucy.ac.cy/architect). 

1. Sign-In with a Google account
2. Pan the map to the location of the building you wish to map
3. Upload an image of the floor plan(s) of your building (If it's a big building, it might take a while to align the floor plan image(s) with the building representation on Google Maps, but even if it's not perfectly aligned, this won't affect indoor positioning performance later.)
4. Put Points of Interest on your floor plans (e.g. the entrance, rooms, stairs, etc) 
5. Connect Points of Interests between them to form paths in your building. These paths will be used by the Anyplace navigation algorithm to draw routes from point A to point B.

### **Step 2:** Record RSS measurements _inside_ the building. 

This happens with the help of the [Anyplace Android application](https://play.google.com/store/apps/details?id=com.dmsl.anyplace&hl=en) and you have to be **physically present** inside the building.

1.  Initiate the Logging process through the Android application and walk around the building. As a best practice to produce more accurate results, walk along long, straight lines (e.g. corridors) 2-3 times. The app will record Wi-Fi Radio Signal Strength measurements along the paths you've walked.
2. Upload the RSS Log (through the app.)
3. It might take a while for the Radiomap to be compiled (if it's a brand new building,) but once it's ready, you can use the Navigator side of the Android application to test the accuracy of indoor positioning. If everything went as expected, you should see the blue pin within a ~2 meters radius from your actual position in the building.

Let me know if I need to clarify any of the above points. Thanks.

**Comment by anyplaceucy** [comment]
The notes also appear under the WIKI page: 

https://github.com/dmsl/anyplace/wiki/How-to-use-the-app---Execute-radio-measurements-by-Kyriakos-Georgiou

**Comment by neofytos** [comment]
Hello Kyriakos,

Thanks for your answer.

I have uploaded a floor plan and then I wanted to update the top view. I deleted the old floor plan and then I uploaded the new floor plan and I drew the POI and paths again. When I start the Logger to try to select the building , the app is showing to me the old floor plan at the wrong position. Although, it is showing the POI on the correct positions. The building is named Alpha Mega Engomi. What is happen? Is a server problem? The viewer is showing  the floor plan and POI correctly.

**Comment by kgeorgiou** [comment]
I assume the old floor plan is cached on the phone.

Try the following to clear the cache:

#### 1. Preferences:
![any1](https://cloud.githubusercontent.com/assets/4765455/25465942/8103e874-2ad3-11e7-89e3-9af97b446093.png)

#### 2. Clear cached floor plans:
![any2](https://cloud.githubusercontent.com/assets/4765455/25465945/86891ef4-2ad3-11e7-9a3c-e8a9fbfd2e27.png)

It should now load your updated floor plan. Let me know how it goes.

**Comment by neofytos** [comment]
Hello Kyriakos,

I have done that and the problem is still appears...

**Comment by constambeys** [comment]
Hello neofytos

If they appear incorrectly in web viewer as well it means that the android app works as expected. If the web viewer is correct I will help you solve the problem with the android app

**Comment by neofytos** [comment]
In the web viewer the top view is at the correct point. In the android app , when I am trying to load the top view , is appeared incorrect.

I have used the choice of cache clearing but nothing is happened.

**Comment by constambeys** [comment]
Check https://github.com/dmsl/anyplace/issues/68 for this issue and try resetting the floor plan using the suggested workaround
