### ISSUE TITLE
Local server issue

### ISSUE THREAD

**Issue by Fullg0lden** [dmsl/anyplace#124]
Hello,
I'm working on your wonderfull application and I try to make your server work localy on my MAC. That was complicated for me to make couchBase work properly and I hope it will work. 

Now I'm trying to set a local server on MAC by using the code you left on github. I'm running the server with "play" and i configured the **application.js** file in config repertory : 

![capture d ecran 2017-04-20 a 17 16 50](https://cloud.githubusercontent.com/assets/27278433/25238248/31f88266-25ed-11e7-9da3-cff70ff35b3f.png)

I imported all the views needed in couchbase and it seems to work. But when I run the project, an unexpected exception occured : 
![capture d ecran 2017-04-20 a 17 14 17](https://cloud.githubusercontent.com/assets/27278433/25238159/eb825762-25ec-11e7-8978-7a179dfff221.png)

I'm facing problems from the beginning but there i'm really blocked. Could you please give me some advices?

**Comment by kgeorgiou** [comment]
Hello @Fullg0lden,

- Which version of Couchbase is that? 
- By taking a quick look at the error, try prepending the scheme **http://** to make it **http://127.0.0.1:8091/pools** and let me know if you're still getting the same error.

**Comment by Fullg0lden** [comment]
Hello,
Thanks for the quick answer :).

The Couchbase version is 3.0.0.

How can I prepend the scheme ?

**Comment by anyplaceucy** [comment]
Anyplace for Couchbase 3.0.0 will be released soon. Please stay tuned. For the moment use the older Couchbase version.

**Comment by Fullg0lden** [comment]
But there is no older version of Couchbase Available. How can I get an older on on MAC?

**Comment by anyplaceucy** [comment]
Check this thread: https://github.com/dmsl/anyplace/issues/107
