### ISSUE TITLE
Using the Navigator and location positioning

### ISSUE THREAD

**Issue by elmustaphah** [dmsl/anyplace#126]
I know that Anyplace uses WiFi positioning. I only used Architect to add my building and floors, nothing else. If I download the Anyplace App on my phone and try to navigate in the building, will it still use WiFi positioning? Sometimes the location is not accurate at all which is making me think that this position data is GPS retrieved.

Thanks.

**Comment by anyplaceucy** [comment]
The Android Navigator uses the default Operating System location until the Anyplace Radiomaps are downloaded to the smartphone. It then switches over to the Anyplace localization algorithms. The radiomaps are cached on the smartphone after the first use, but they can be synced through the navigator menus)
