### ISSUE TITLE
Changing location, multiple Maps and incorrect POI positions 

### ISSUE THREAD

**Issue by elmustaphah** [dmsl/anyplace#127]
![fullsizerender](https://cloud.githubusercontent.com/assets/25204069/25503529/aeab12ce-2b92-11e7-86ee-be00b7ec0f0a.jpg)
POI are showing in incorrect positions from what i have set, when I try to zoom in to try and fix this problem I get multiple maps.
Location keeps checking as well, why is this?

Regards

**Comment by constambeys** [comment]
If the POIS are shown incorrectly in Web Viewer as well it means that something went wrong and they are not configured correctly. Try setting the floor plan first and then configure the pois

**Comment by eduamf** [comment]
How to set the correct position of building plan? How to mark the walls? I want to use AnyPlace to help blind people.

**Comment by dzeina** [comment]
You have to add some POIs and connect them. Navigation will only be available over the topology you create. Please see the architect video for more details
