### ISSUE TITLE
Is it your service or server down??

### ISSUE THREAD

**Issue by hunain24** [dmsl/anyplace#128]
I have use your api in my project but it is not working following message is showing ,

anyplace.rayzit.com refused to connect.

Kindly look into this matter

Thank you.

**Comment by Costantinos** [comment]
Hello @hunain24 ,
Could you please check it now?
Thanks,
C.

**Comment by hunain24** [comment]
Thank you so much it is working now

**Comment by zaid93** [comment]
Hello today when i try to open anyplace it show anyplace.rayzit.com refused to connect.
I'm using it for my project and i can't open it. Help me

**Comment by hunain24** [comment]
Hey,

I just signed the petition "www.nobelpeaceprize.org/: Nomination of Prime
Minister of Pakistan, Mr. Imran Ahmed Khan for the Nobel Peace Prize" and
wanted to see if you could help by adding your name.

Our goal is to reach 150,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/4qmDxnykHS

Thanks!
Hunain

**Comment by anyplaceucy** [comment]
Please only post issues relevant to the anyplace stack on this forum.
