### ISSUE TITLE
inquiries

### ISSUE THREAD

**Issue by ebtsam2016** [dmsl/anyplace#13]
I am a student and I have some inquiries about the application, but my English is not quite good
and I want to help

**Comment by dvaler01** [comment]
We are here if you need help :)
Dimitrios Valeris

**Comment by ebtsam2016** [comment]
This code when put on compiler eclipse and enter the libraries give me an error

**Comment by constambeys** [comment]
Hello ebtsam2016
Make sure you have read the readme file and check that you did the steps mentioned. If the error message remains  contact us again with more details (procedure and the error message)
Timotheos

**Comment by ebtsam2016** [comment]
To enter actionbarsherlock , google-play-services_lib ,library and android-support-v4.jar to project Anyplace 
I make the following steps  
1- press right click on project and choose properties 
2-choose Resourse and android
3-Add all libraries (actionbarsherlock , google-play-services_lib ,library and android-support-v4.jar)
but diplay me mark ( ! ) in project
Where error ???

**Comment by constambeys** [comment]
Don't add all libraries to the Anyplace Project.
Make sure you have the following settings:
Anyplace Project - Properties - Android
  - actionbarsherlock
  - library

Library Project - Properties - Android
  - google-play-services_lib
Library Project - Java Build Path- Libraries
  - android-support-v4.jar - ReadMe

Actionbarsherlock Project - Java Build Path- Libraries
  - android-support-v4.jar - ReadMe

In addition do the following:
1 - Project Actionbarsherlock  properties
2 - Choose Java Build Path
3 - Order and Export 
4 - Check android-support-v4.jar 

Check these steps and let me know if it is fixed

**Comment by ebtsam2016** [comment]
how to enter android-support-v4.jar - ReadMeto eclipse

**Comment by constambeys** [comment]
Import the ReadMe project similarly with the other projects
Then use the add jars option to add the jar

**Comment by ebtsam2016** [comment]
thanks you to help me to  fix the error  :)

**Comment by constambeys** [comment]
no problem

**Comment by ebtsam2016** [comment]
In order to run this application must have a Google internal drawing of the building

**Comment by constambeys** [comment]
What do you mean? Can you explain it again?

**Comment by ebtsam2016** [comment]
Is this application can be implemented anywhere?

**Comment by constambeys** [comment]
In the logger's settings you have the option to add your own building. Yes you need a top view of the building and then using the logger you have to collect wifi fingerprints. For more information about wifi fingerprints see the wiki article "Best-Practices-for-producing-WiFi-Radiomap-In-Anyplace-Android".

**Comment by ebtsam2016** [comment]
I can not understand how the application works
Does he have to stand over the building in order to be to know my location is then to know the internal drawing of the building ?? 

What are the steps to determind my location and knowledge of internal drawing of the building ??

**Comment by dzeina** [comment]
Please check http://anyplace.cs.ucy.ac.cy/ for the steps (there are video explanations for each step).  Please don't abuse this section with questions that are answered on the website.
