### ISSUE TITLE
License declaration

### ISSUE THREAD

**Issue by azzamsa** [dmsl/anyplace#130]
what is the license of this application ?

would you please provide license of this application explicitly. Because there are some incompatible issue between various Free Software / Open Source Licenses when we use in production.

**Comment by anyplaceucy** [comment]
Its MIT (written clearly on the github page).

**Comment by azzamsa** [comment]
I am sorry, cause I just check the existence of License file. so that I don't find MIT written in your repo header.

thanks for help.
