### ISSUE TITLE
Regarding for Mapping (Authorization required)'s API

### ISSUE THREAD

**Issue by zitinghan** [dmsl/anyplace#131]
Hi,

I would like to know where can I get the 'Authorization required' API. Isn't under architect > more > your api key?

Thanks.

**Comment by anyplaceucy** [comment]
Its under https://anyplace.cs.ucy.ac.cy/developers/ 
Not all calls require the key

**Comment by zitinghan** [comment]
Thanks, but how can I become a developer?
