### ISSUE TITLE
AnyPlace Viewer

### ISSUE THREAD

**Issue by ilango123** [dmsl/anyplace#133]
Hi
I got the Anyplace viewer working on localhost:8080 in the browser. I am able to display the map of the world alright but what are INDEED displayed now are those circles with numbers in them.

![capture4](https://cloud.githubusercontent.com/assets/25613858/26537595/793497b4-4406-11e7-95d3-ecd636680e56.JPG)

What I do not understand is, where is all that data in the dropdown coming from? How can I bring my  own data in. 
Where in the code can I look to find out where that data is coming from?

thanks

**Comment by anyplaceucy** [comment]
See the latest release notes on setting up your own couchbase: https://github.com/dmsl/anyplace
