### ISSUE TITLE
Anyplace viewer issue

### ISSUE THREAD

**Issue by niteesh123** [dmsl/anyplace#135]
Hi guys
I got the Anyplace viewer working on localhost:8080 in the browser. I am not able to display location pins on the map.
thanks.. 

![cab1b8b2-30f4-4a4a-8e2c-7de77f5206d0](https://cloud.githubusercontent.com/assets/25248341/26668552/da992240-46c7-11e7-8758-87cd583f79d7.jpg)

**Comment by ilango123** [comment]
Niteesh, I had that issue also. It is now resolved. Open the Developer console in Chrome. You should see the errors. Post a screenshot from Chrome Console and I can help you out with this

**Comment by anyplaceucy** [comment]
Fixed in Anyplace v3. For more check the github page: https://github.com/dmsl/anyplace
