### ISSUE TITLE
POST https://server/anyplace/mapping/accounts/sign 403 (Forbidden)

### ISSUE THREAD

**Issue by KalimdorTheKing** [dmsl/anyplace#136]
Hi,
I have builded anyplace server and I changes googleapi settings (api key, client-id) in architect and viewer index.html files. Finally, I see requests without any problem to my google apis. But I have a new problem which I did not have before, I can't add/listing vs. methods. I always getting 403 Forbidden code. How can I resolve this problem? Is there orher configurations about google authentication or parameters connected with authentication. 

I see same error after each request on server console.
**[error] application - LPLogger::Error:: java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"**

Many Thanks.

**Comment by KalimdorTheKing** [comment]
Solution below;
This issue was occured after hosting server with https. General proxy settings and play framework conf settings are not enough to solve this problem. Only the code below solved problem. I have written it into server/app/controllers/AnyplaceMapping.java ( sendGet ) method.

```
Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("proxyserverip", proxyport));
        Authenticator authenticator = new Authenticator() {

                public PasswordAuthentication getPasswordAuthentication() {
                        return (new PasswordAuthentication("Iusername","Password".toCha$
                }
        };
        Authenticator.setDefault(authenticator);
```

**Comment by anyplaceucy** [comment]
Fixed in Anyplace v3. For more check the github page: https://github.com/dmsl/anyplace
