### ISSUE TITLE
Android - bad floor map scalling

### ISSUE THREAD

**Issue by Sukiennik** [dmsl/anyplace#138]
Hi. I read last issues about this bug but even after following these workaround advices (adding map on max zoom Map in Viewer, deleting cache on android app and loading buildings once again) it is still scalled in the wrong way. On low zoom it is too small, on the max zoom too big and often moved far away from real building on gmaps.

My building: "d17"

Thanks for help.

**Comment by anyplaceucy** [comment]
You probably just didn't purge your caches on Android correctly. Check your in-app settings.
