### ISSUE TITLE
Building the distribution package gives a "viewer" page without js, css or images (v3.0a αr)

### ISSUE THREAD

**Issue by emptymatt** [dmsl/anyplace#144]
Hi,
I've cloned the project, installed npm, bower, java 1.8 and sbt 0.13.15, checkout in the "develop" branch.
Then "bower install && npm install && grunt" in the architect and viewer directory.
I've launched the project in **dev mode** ("run" command in the sbt shell in the server directory) **and everything was fine**.

Then **I've built the project** ("dist" command in the sbt shell), I have extracted the .zip file just created and then launched the server (as described in the readme).
In this **production** mode the architect page works well, but the viewer page is like the following: 

![9111cf80](https://user-images.githubusercontent.com/22802639/28500787-e7a9d27e-6fce-11e7-8298-5aec5ac09abe.png)

The dev tools show only 500 http code for JavaSctip, CSS and png files.
I've followed the errors log and inspected the lib/anyplace_scala.anyplace_scala-1.0-assets.jar, but no structural difference between architect and viewer. :/

An example of the error the server tells me:

> ! @74m23knoa - Internal server error, for (GET) [/viewer/bower_components/angular-ui-select/dist/select.css] -
>  
> play.api.UnexpectedException: Unexpected exception[FileNotFoundException: file:/home/anyplace/server/target/universal/anyplace_scala-1.0/lib/anyplace_scala.anyplace_scala-1.0-assets.jar!/public/anyplace_viewer/bower_components/angular-ui-select/dist/select.css (No such file or directory)]
> 	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
> 	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
> 	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
> 	at play.core.j.JavaGlobalSettingsAdapter.play$core$j$JavaGlobalSettingsAdapter$$super$onError(JavaGlobalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
> 	at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onError$2.apply(JavaGlobalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
> 	at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onError$2.apply(JavaGlobalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
> 	at scala.Option.getOrElse(Option.scala:121) [org.scala-lang.scala-library-2.11.7.jar:na]
> 	at play.core.j.JavaGlobalSettingsAdapter.onError(JavaGlobalSettingsAdapter.scala:36) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
> 	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
> 	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:158) [com.typesafe.play.play-netty-server_2.11-2.4.2.jar:2.4.2]
> Caused by: java.io.FileNotFoundException: file:/home/anyplace/server/target/universal/anyplace_scala-1.0/lib/anyplace_scala.anyplace_scala-1.0-assets.jar!/public/anyplace_viewer/bower_components/angular-ui-select/dist/select.css (No such file or directory)
> 	at java.io.FileInputStream.open0(Native Method) ~[na:1.8.0_131]
> 	at java.io.FileInputStream.open(FileInputStream.java:195) ~[na:1.8.0_131]
> 	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[na:1.8.0_131]
> 	at play.api.libs.iteratee.Enumerator$.fromFile(Enumerator.scala:584) ~[com.typesafe.play.play-iteratees_2.11-2.4.2.jar:2.4.2]
> 	at play.api.mvc.Results$Status.sendFile(Results.scala:416) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
> 	at controllers.AnyplaceAssets$$anonfun$at$1.apply(AnyplaceAssets.scala:62) ~[anyplace_scala.anyplace_scala-1.0-sans-externalized.jar:na]
> 	at controllers.AnyplaceAssets$$anonfun$at$1.apply(AnyplaceAssets.scala:46) ~[anyplace_scala.anyplace_scala-1.0-sans-externalized.jar:na]
> 	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:408) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
> 	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:407) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
> 	at play.api.mvc.Action$.invokeBlock(Action.scala:533) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
> [[31merror[0m] application - 

Any idea of what causes this error in viewer but not in architect?

**Comment by Costantinos** [comment]
Hello @emptymatt ,

Could please choose angular 1.3.20 during the building process and try again?

**Comment by emptymatt** [comment]
I was indeed using the 1.2.32 version but even with 1.3.20 it's the same :(
The version should be hardwritten in the bower.json.

Note that for me I have also this problem when I launch the project in the zip file you've uploaded in the commit a0ae190.

**Comment by Costantinos** [comment]
We have published an updated release that solves the issues.
