### ISSUE TITLE
Want to roll this out at my university but they are concerned about user data being leaked to Google.

### ISSUE THREAD

**Issue by lyle-univ** [dmsl/anyplace#145]
I am very keen on getting this up and running at our campus.

I would just like to confirm if information about users making use of navigation stays within the confines of the system. That is, this information is not send to Google by virtue of it making use of Google maps.

User privacy is the main concern my university has and they would not want it deployed if the user data does not remain private.

**Comment by anyplaceucy** [comment]
Anyplace uses standard smartphone localization (WiFi, Cellular, etc) for its bootstrapping process. It is known that these localization requests reach either Google, Microsoft or Apple localization services. How this is used is not known. However, this is not beyond what normal apps use and a user is supposed to have the option to turn location off on any of these platforms (its just that they location of the user will not show up on a map).

**Comment by lyle-univ** [comment]
Thanks for the feedback. Would AnyPlace be at all usable when turning localization services of and relying entirely on Wifi and IMU sensors?

**Comment by anyplaceucy** [comment]
Yes, it will work ok.

Its just that the initial localization will take more time as the user has to select which building he is currently at and then Anyplace will download the respective radiomaps (from the Anyplace service you will be controlling) for fine-grain localization.
