### ISSUE TITLE
new anyplace_v3 for administrator's .bat file closes immediately

### ISSUE THREAD

**Issue by isener** [dmsl/anyplace#147]
At first I'm newbie at Play Framework and Java Development (I'm originally javascript developer)
I followed the instructions on /server readme.md
Installed couchbase 4.6 and edited application.conf file through connection to it.
After all I started the .bat file, but it immediately closes.

Here is the log file 

`2017-08-06 22:32:14,302 [WARN] from application in main - Logger configuration in conf files is deprecated and has no effect. Use a logback configuration file instead.`
`2017-08-06 22:32:16,713 [INFO] from play.api.libs.concurrent.ActorSystemProvider in main - Starting application default Akka system: application`
`2017-08-06 22:32:16,928 [INFO] from application in main - Global::onStart():: AnyPlace Application started
`

**Comment by anyplaceucy** [comment]
You have to open a command line (CMD or Powershell) and run the batch file from there (not simply double click on it). This is standard practice in windows for running batch files.
