### ISSUE TITLE
Couchbase view update

### ISSUE THREAD

**Issue by Mirdox** [dmsl/anyplace#149]
Hello,

First of all, thanks for this great project.

I'm trying to deploy own instance of anyplace, but I have some issues.

For example: Internal Server Error, when adding POI.
I've managed to fix it (hopefully) by modifying Poi.scala:
    def getId(): String = {
        var puid: String = fields.get("puid")
        if (puid==null || puid.trim().isEmpty || puid == "") {
            puid = Poi.getId(fields.get("username_creator"), fields.get("buid"), fields.get("floor_number"), fields.get("coordinates_lat"), fields.get("coordinates_lon"))
            fields.put("puid", puid)
            this.json.put("puid", puid)
        }
        puid
    }

Now I'm dealing with problem, that changes in Architect are not visible in Viewer.
There are no errors in web console or server, but I've find out that it may be related to view definitions in couchbase.

For example accounts_all view definition contains doc.doctype, while documents contain "doc_type": "account".

Could you please confirm, that this could be problem and release correct views definition?

Thank you.

**Comment by Costantinos** [comment]
Hello,

Sorry for the delayed reply. There was a small bug at Poi class. The develop branch has been updated.
