### ISSUE TITLE
AnyPlaceTilerHelper.scala - storeFloorPlanToServer - is not working

### ISSUE THREAD

**Issue by dsudheer** [dmsl/anyplace#150]
Hi Team Team.
I see below code is not working. I have added some loggers and change in file copy logic still no luck. we are getting 'dest_f' as null at the end. Can someone check whats wrong with below code?

AnyPlaceTilerHelper.scala
def storeFloorPlanToServer(buid: String, floor_number: String, file: File): File = {
val dirS = AnyPlaceTilerHelper.getRootFloorPlansDirFor(buid, floor_number)
val dir1 = new File(dirS)
dir1.mkdirs()
if (!dir1.isDirectory || !dir1.canWrite() || !dir1.canExecute()) {
throw new AnyPlaceException("Floor plans directory is inaccessible!!!")
}
val name = "fl" + "_" + floor_number
LPLogger.info(dir1.getAbsolutePath() +"/"+ name);
val dest_f = new File(dir1.getAbsolutePath() +"/"+ name);
LPLogger.info("dest_f.getAbsolutePath():"+dest_f.getAbsolutePath());
var fout: FileOutputStream = null
fout = new FileOutputStream(dest_f)
fout.close()
LPLogger.info("file.toPath()"+file.toPath());
Files.copy(file.toPath(), dest_f.toPath())
// println(dest.getAbsolutePath())
// Files.copy(file.toPath(), fout)

    LPLogger.info("dest_f:"+dest_f);

    dest_f
}
Thanks,
Sudheer

**Comment by Mirdox** [comment]
Hi,

I had problem with uploading floor plans too.
Have you tried "develop" branch, it worked for me.

BR

**Comment by dsudheer** [comment]
Yes. but no luck. dest_f is coming as null.
Thanks
Sudheer

**Comment by dsudheer** [comment]
Fixed the copy file code. Might this fix only for Ubuntu 16.04. Successfully creating floor image, but now in the list of buildings stored one is not coming. Something else is the issue.

Fixed code:
=========
    def storeFloorPlanToServer(buid: String, floor_number: String, sourceFile: File): File = {
    var destFile: File = null
    try {
        Logger.info("sourceFile.toPath:"+sourceFile.toPath,null)

        if(!sourceFile.exists()) {
            throw new AnyPlaceException("sourceFile.exists():"+sourceFile.exists())
        }
        //val destFile = null;
       // var destFile: File = null
        val dirS = AnyPlaceTilerHelper.getRootFloorPlansDirFor(buid, floor_number)
        Logger.info("dirS:"+dirS, null)
        val targetDir = new File(dirS)
        targetDir.mkdirs()

        Logger.info("targetDir.isDirectory :"+targetDir.isDirectory , null)
        Logger.info("targetDir.canWrite():"+targetDir.canWrite(), null)
        Logger.info("targetDir.canExecute():"+targetDir.canExecute(), null)

       /* if (!targetDir.isDirectory || !targetDir.canWrite()) {
            throw new AnyPlaceException("Floor plans directory is inaccessible!!!")
        }*/

        val fileName = "fl" + "_" + floor_number
        Logger.info("sourceFile.toPath::"+sourceFile.toPath)
        destFile = new File(targetDir, fileName)
        Logger.info("destFile.toPath1:"+destFile.toPath, null)
        Files.copy(sourceFile.toPath, destFile.toPath)
        Logger.info("destFile.toPath4:"+destFile.toPath, null)
        } catch {
            case unknown => Logger.info("Got this unknown exception: " + unknown, null)
        }
        destFile
    }
