### ISSUE TITLE
Viewer - position raw data

### ISSUE THREAD

**Issue by efaehse** [dmsl/anyplace#151]
The Anyplace Android Viewer App shows me my estimated position on the map. What is the best way to collect the raw data of it?

I like to specify the error of my position and raw data would be very helpful for this.

**Comment by anyplaceucy** [comment]
https://github.com/dmsl/anyplace/wiki/Best-Practices-for-producing-WiFi-Radiomap-In-Anyplace-Android-by-Christos-Laoudias
