### ISSUE TITLE
How to deploye anyplace to your local server?

### ISSUE THREAD

**Issue by echo1123** [dmsl/anyplace#152]
Hi,
I want to deploye anyplace to your local server.When I try to run revised codes ,I always getting 403 Forbidden code. How can I resolve this problem?

I see same error after each request on server console.
[error] LPLogger::Error:: java.net.ConnectionException: Connection timed out : connect
#136
![1](https://user-images.githubusercontent.com/31124571/29450612-e552386e-8431-11e7-8110-eaf2f7952db7.png)
![3](https://user-images.githubusercontent.com/31124571/29450632-05f4d630-8432-11e7-85e9-9ceaeb50f0ef.png)

Many Thanks

**Comment by Costantinos** [comment]
Did you install the couchbase server?

**Comment by anyplaceucy** [comment]
Check the latest release v3.2 and report if issue has not been addressed.
