### ISSUE TITLE
Using Anyplace in my research project

### ISSUE THREAD

**Issue by bojan2110** [dmsl/anyplace#153]
Hi! 

Compliments on your project, looks really nice! For my own PhD research, I am developing an Android app where among other things, I want to log user's movement around a building. Is it possible to do this by using some components of your project?

And if so, where would you recommend for me to start?

I was thinking to do the Architect and the logging part by myself, and when 'real' users come, just log their location based on the system I set up. Is this one possibility to start with?

**Comment by bojan2110** [comment]
Just to make it more clear, I want to use the project in an non intrusive way for my users. So they wouldn't be shown any indoor map or tracking path, I just want to periodically ( lets say every minute) track their indoor location, based on the map I will build myself.

**Comment by anyplaceucy** [comment]
You have to adapt the navigators to achieve this. There are no ready made modules for tracking users in Anyplace
