### ISSUE TITLE
POI is are not adding, If we run from batch file. anyplace_v3.bat

### ISSUE THREAD

**Issue by malavcygnet** [dmsl/anyplace#156]
Hello Team, today we have tried to setup everything. and there are some issues which we are facing related to below points.

1. When we run direct batch file for server code, after setting database config then POIs are not adding. so kindly provide solutions for that.

2. And i think you have used gitignore for build folder. and in some place CSS and JS you have taken from build folder. so code has not been complete committed and pushed on server. so we request you to provide complete code. so that we can install on our server and can test properly.

**Comment by sreejith-ms** [comment]
#182

**Comment by Costantinos** [comment]
The anyplace_v3.zip has been updated.
