### ISSUE TITLE
"No Internet Connection" message when using Anyplace with cellular data

### ISSUE THREAD

**Issue by laoudias** [dmsl/anyplace#157]
When using the Anyplace application with cellular data connection the "No Internet Connection" message keeps coming up asking to turn on WiFi connection (see screenshot). However, the content (floor plans, POIs, etc.) loads just fine and the application runs smoothly.

![screenshot_20170828-172232](https://user-images.githubusercontent.com/1115957/30022970-4e7efec0-9176-11e7-9c32-954492c35e29.png)

**Comment by constambeys** [comment]
It is a safety check to ensure the wifi is enabled and wifi samples are collected. The error is somehow wrong since is complaining about internet connectivity. Should I change it?

**Comment by anyplaceucy** [comment]
It would be best if the user would get after the first "NO" response a  button in red on the upper right corner of the screen with the reading: "OFFLINE" (once clicked, it should try to connect again).

**Comment by laoudias** [comment]
Maybe a message saying something like "WiFi is disabled - Turn on for optimal performance" could be used, instead of "No Internet Connection". Anyway, some smartphones (like the one above) do scan WiFi APs even if the user has not explicitly turned on WiFi.

**Comment by constambeys** [comment]
fixed in version 2.4.0
