### ISSUE TITLE
AnyPlace on Windows Server

### ISSUE THREAD

**Issue by mohammedsajid** [dmsl/anyplace#159]
Can we publish anyplace service on windows server? If yes then kindly provide documentation.

**Comment by anyplaceucy** [comment]
Yes, anyplace runs on windows. You have to start it using the provided .bat file.

https://anyplace.cs.ucy.ac.cy/downloads/anyplace_v3.zip  

You can follow the installation instructions here: https://github.com/dmsl/anyplace/tree/master/server
