### ISSUE TITLE
Designing for High Availability and Scaling of AnyPlace

### ISSUE THREAD

**Issue by greenm3** [dmsl/anyplace#160]
I have a site that will have about 600 access points that are OpenWRT with a low density of users (200). Why so low? Because the wifi is for construction site.  Over time on this one site there could be 7 buildings so could be over 4,000 access points if the APs stay permanent after construction as we would transition the construction wifi for building IOT and facility maintenance wifi.

With this many APs, bringing all the RSSI logs into one place could be a challenge. Especially if we want real time location services.

The site is a large data center so availability and performance is critical.

What has the AnyPlace team done to address High Availability and Scalability issues?

Is there a concern from the team on how to handle 4,000 APs providing real time RSSI updates?

What are recommended options for designing the platform to account for outages and maintenances events which are highly likely at a construction site?

**Comment by anyplaceucy** [comment]
Anyplace has been written from ground up for High Availability  (e.g., the public setup runs on a cluster of document stores, uses a load balancer, etc.) Many of these developments are documented in an upcoming article presented in the ACM SIGSpatial Special magazine (soon to be linked on the anyplace website).
