### ISSUE TITLE
AnyPlace server V3 update 

### ISSUE THREAD

**Issue by AkhilChandi** [dmsl/anyplace#161]
Hello,
          First of all my sincere thanks to anyplace people for indoor navigation system.   i am using the anyplace indoor navigation system for my academic project , and i found the code for the same in your git hub too,but the updated version of code for the server module was written in Scala,and found the older version in java also currently i am using the java server . Can i expect the updated version(V3) in java or not?.

Thanks.

**Comment by anyplaceucy** [comment]
Unfortunately no, only the Scala version will be updated from now on.
