### ISSUE TITLE
Using beacons with anayplace

### ISSUE THREAD

**Issue by fobus42** [dmsl/anyplace#162]
Hello, First thank you for this great project.

I'm interested in using this project with IOS devices. As you know it is not allowed listening wi-fi data with IOS devices. But we are able to communicate with beacons on IOS devices. 

So I'm wondering if I am able to work with beacons. So, I get distances of beacons.

What do you think? am I able to work with anyplace and beacons with small minor changes. Or anyplace is designed to work only with wi-fi data?

I will have bacons fingerprint and distance, do I need any thing other?

Thank you.

**Comment by anyplaceucy** [comment]
It is absolutely possible. This was in fact a past target, but never realized. Anyplace would be interested to get such developments integrated to its main stack.
