### ISSUE TITLE
Builiding image 

### ISSUE THREAD

**Issue by GregorioF** [dmsl/anyplace#163]
Hi, i have a problem whith loading the image of the building where i work in "https://anyplace.cs.ucy.ac.cy/architect/".  
When i do it in the page everything is ok, the terrain matches with the plan, and  in the viewer seems ok. But after i enter with my cellphone, i  download the building, and the image is alot smaller that the terrain.

Anyone else with this problem ?

**Comment by anyplaceucy** [comment]
See
https://github.com/dmsl/anyplace/wiki/Markers-in-map-(viewer)-are-displayed-wrong
