### ISSUE TITLE
Couchbase default port

### ISSUE THREAD

**Issue by abhilash1in** [dmsl/anyplace#167]
Documentatioin of server installation says default port of Couchbase is 8092. However, `application.conf` has `couchbase.port=8091`

https://github.com/dmsl/anyplace/blob/b20f5e09e4ce2c9e23ca6a82895786e20afcd4e7/server/conf/application.conf#L75

https://github.com/dmsl/anyplace/blob/b20f5e09e4ce2c9e23ca6a82895786e20afcd4e7/server/README.md#L25

**Comment by Costantinos** [comment]
Hello,
The 8092 is used for the UI port. The port 8091 is used for the Couchbase REST API. So you should use the 8091 port.

**Comment by abhilash1in** [comment]
So, shouldn't it be corrected in the README?

**Comment by Costantinos** [comment]
Yes. The README file is already updated.

**Comment by abhilash1in** [comment]
Awesome! Thanks!
