### ISSUE TITLE
Fetching buildings

### ISSUE THREAD

**Issue by sauloco** [dmsl/anyplace#17]
I can't see the building I've created in Architect from Android Viewer.
I made the building public, but still not showing.
When I try to fetch the buildings from the app I see a toast with the error: 
> Cannot connect to Anyplace service!

My building:
CODE: MUNI_OLAV
Title: Municipalidad de Olavarría
Description: Oficinas municipales

Can you give me a hint to solve it?

**Comment by dvaler01** [comment]
Try to delete and install again the app. 
This is a bug that we will fix it in the future.
I am pretty sure this will solve your problem.

We are here for further help. :)
Dimitrios Valeris.

**Comment by sauloco** [comment]
Great. Working now :+1:
