### ISSUE TITLE
Couchbase CE 5.0

### ISSUE THREAD

**Issue by EmrahKK** [dmsl/anyplace#178]
Hi,

We get problem while we try to connect couchbase ce 5.0. Is there any change for  couchbase ce 5.0 version.

config;

couchbase.hostname="http://localhost"
couchbase.port=8091
couchbase.bucket="anyplace"
couchbase.username="user"
couchbase.password="passs"

**Comment by JeffOnGithub** [comment]
Just got the same issue, the user and the bucket must be the same otherwise it won't work, there is a new security management system in Couchbase 5

**Comment by dikobagda** [comment]
Create match data between username and bucket's name. On Couchbase 5.0 CE they upgrade Role Based Authentication. here the news https://forums.couchbase.com/t/v5-0-new-role-based-authentication-bucket-passwords-etc/14637?u=jkurtz

<img width="522" alt="screen shot 2018-02-20 at 12 01 55 pm" src="https://user-images.githubusercontent.com/1335894/36408145-1d019da4-1636-11e8-9afb-7a57e222bcf7.png">
