### ISSUE TITLE
Implementation guide?

### ISSUE THREAD

**Issue by beattyr** [dmsl/anyplace#179]
Forgive me if this information is already available, I searched the forum/issues and did not see anything that specifically seemed to cover this, perhaps I looked in the wrong place?

Is there an implementation guide or post that describes the setup from start to finish for not only the app, but more importantly to the architect side?

I am looking for the steps that are needed to take a device with the app loaded on it into a new building and when the process is complete, have a fully mapped building giving accurate location.

Additionally, can building maps be kept privately? I watched the video on the architect and i wasn't sure if the map that was being added to was publicly available or not.  I am looking at implementation in facilities that may not want their entire buildings layout made fully public.

Thank you!

**Comment by anyplaceucy** [comment]
Please check under Wiki for the fingerprinting guide. There is no detailed guide for the archtitect yet. Buildings can be kept private through the respective check box in the Architect. You can even run the Anyplace stack on your own server and have it isolated from the outside world.
