### ISSUE TITLE
Running Anyplace on own server..rendering issues..

### ISSUE THREAD

**Issue by mathurabhishek** [dmsl/anyplace#183]
I have built the server package using IntelliJ IDE as given in instructions and I am trying to run architect and viewer on my own server. The build and run is successful but when I open Architect and Viewer apps using http://localhost:9000/architect/ and http://localhost:9000/viewer/ they don't get rendered properly.
Browser is not able to locate several .css , .js and .png's required for rendering. Am I missing something in the build step? Please help.
![architect_error](https://user-images.githubusercontent.com/5594541/33570012-84f5f18e-d951-11e7-9ef8-d49ae948b181.png)
![viewer_error](https://user-images.githubusercontent.com/5594541/33570013-852c22ea-d951-11e7-8d2f-98d0a29a225f.png)

**Comment by mathurabhishek** [comment]
Got the resolution for this. The architecture and viewer apps have to be built separately. They don't get built along with the server in intelliJ IDE. Dependencies have to be resolved using npm, bower and grunt.
Steps are here: 
https://github.com/dmsl/anyplace/tree/master/server/public/anyplace_viewer
https://github.com/dmsl/anyplace/tree/master/server/public/anyplace_architect

**Comment by BHARGAVISUDHAKAR** [comment]
Hi mathurabhishek. Could you tell me how you generated the application secret in playframework as given in the instructions. 

![anyplace server](https://user-images.githubusercontent.com/51232568/59009616-e020e180-8860-11e9-9975-d7455164c049.JPG)
