### ISSUE TITLE
Unable to connect android app to local server

### ISSUE THREAD

**Issue by mathurabhishek** [dmsl/anyplace#184]
Using anyplace_v3_0_5
Downloaded the android app from playstore. Tried connecting it to the local server by changing the ip address through Preferences -> Anyplace Server IP Address option.
Doesn't work.  Tried different formats (http://x.x.x.x , x.x.x.x, http://x.x.x.x:9000). Doesn't work.

Local server has building, floor plan and poi added. POI is added from back end into DB as I was facing trouble in adding it from architect(http://localhost:9000/architect). These are getting displayed  in viewer (http://localhost:9000/viewer)  but not getting displayed in android app when I refresh the map and building in android app. I believe it is because of connectivity problem as explained above. 
Please help.

**Comment by mathurabhishek** [comment]
@Costantinos  could you please help with this issue ..

**Comment by anyplaceucy** [comment]
You would need an ssh certificate through lets-encrypt. see the manual

**Comment by ReedSTL** [comment]
Is there a link to the manual?  All  I can find "Install a free certificate from https://letsencrypt.org/ on your Anyplace Server to obtain a secure https connection. SSL is only optional for web functionality. For Android, SSL is a prerequisite!"  Which doesn't help with how to configure.  I have got a SSL certificate and stored in the JAVA keystore but do not know how to get the server to use it.
Thanks
