### ISSUE TITLE
Anyplace Logger/Navigator User Location

### ISSUE THREAD

**Issue by EmrahKK** [dmsl/anyplace#187]
Hi,
When we try to use Anyplace Logger and navigator it misplacecess location indicator. And this misplacement is very big. It shows user location in the middle of the sea even if we are far from it. How can we fix this.

**Comment by anyplaceucy** [comment]
https://github.com/dmsl/anyplace/wiki/Best-Practices-for-producing-WiFi-Radiomap-In-Anyplace-Android-by-Christos-Laoudias
