### ISSUE TITLE
any place navigate issue

### ISSUE THREAD

**Issue by goutham465** [dmsl/anyplace#188]
hii as of any place we did the process of web version trained there with add building, floor, map loading &adding poi's with connectors and toggle.later in mobile selected show logger option  with biulding mapked gps point started wifi recordings and loaded rss log for building selected  ,later selected building for navigator here the point is iam unable to navigate from my current location to destiny point i.e showing error no entrance found or no valid path exists between poi's.so please kindly reply as soon as possible

**Comment by anyplaceucy** [comment]
One of the the POIs needs to be the tagged as an "Entrance" in Architect.
