### ISSUE TITLE
Android deprecated tools 

### ISSUE THREAD

**Issue by gibranfelix** [dmsl/anyplace#19]
Hi @kgeorgiou and @laoudias.

The library ActionBarSherlock was deprecated and no more development will be taking place. Their developers recommends to use Android AppCompat:
[https://github.com/JakeWharton/ActionBarSherlock](https://github.com/JakeWharton/ActionBarSherlock)

Also Google announced that eclipse support ended. Anyplace should to be migrated Android Studio:
[http://developer.android.com/intl/es/tools/help/adt.html](http://developer.android.com/intl/es/tools/help/adt.html)

I would solved both issues and commit it but it implies a big files reformat. It better that your team solve the issues. 

Greetings.

**Comment by constambeys** [comment]
Ok do the upgrade and we will check it when is done

**Comment by gibranfelix** [comment]
I have migrated the code to android studio if you want i can share the code.

**Comment by constambeys** [comment]
Test it and if it is working do it

**Comment by gibranfelix** [comment]
I have already done the commit on the develop branch and made the pull request. I only migrated the code to android studio
