### ISSUE TITLE
anyplace database views seems to be incorrect

### ISSUE THREAD

**Issue by m6amiri** [dmsl/anyplace#194]
the following is my view file (nav.json):
### 
{
					"views": {
						"pois_by_buid": {
							"map": "function (doc, meta) {\n  if( doc.buid && doc.puid && doc.pois_type && !doc.cuid )\n      //emit(doc.buid, doc);\n    emit(doc.buid, null);\n}"
						},
						"pois_by_buid_floor": {
							"map": "function (doc, meta) {\n  if( doc.buid && doc.puid && doc.floor_number )\n      //emit([doc.buid,doc.floor_number], doc);\n      emit([doc.buid,doc.floor_number], null);\n}"
						},
						"connection_by_buid": {
							"map": "function (doc, meta) {\n  if( doc.buid && doc.edge_type && doc.pois_a && doc.pois_b )\n      //emit(doc.buid, doc);\n    emit(doc.buid, null);\n}"
						},
						"building_all": {
							"map": "function (doc, meta) {\n  if( !doc.puid && !doc.floor_number && !doc.edge_type && doc.buid && doc.is_published == \"true\")\n  \t//emit(meta.id, doc);\n    emit(meta.id, null);\n}"
						},
						"floor_by_buid": {
							"map": "function (doc, meta) {\n  if( doc.floor_number && doc.floor_name && doc.buid && !doc.puid )\n  \t//emit(doc.buid, doc);\n    emit(doc.buid, null);\n}"
						},
						"connection_by_buid_floor": {
							"map": "function (doc, meta) {\n  if( doc.buid && doc.cuid && doc.floor_a && doc.floor_b && doc.floor_a == doc.floor_b )\n    //emit([doc.buid,doc.floor_a], doc);  \n    emit([doc.buid,doc.floor_a], null);\n}"
						},
						"all_by_pois": {
							"map": "function (doc, meta) {\n  if( doc.puid )\n    // delete pois\n  \temit(doc.puid, meta.id);\n  else if( doc.pois_a && doc.pois_b && doc.pois_a != doc.pois_b){\n    // delete connections\n  \temit( doc.pois_a, meta.id );\n    \temit( doc.pois_b, meta.id );\n  }\n}"
						},
						"all_by_floor": {
							"map": "function (doc, meta) {\n  if( doc.buid && doc.floor_number )\n    // delete pois & floor\n  \temit( [doc.buid, doc.floor_number], meta.id);\n  else if( doc.floor_a && doc.floor_b && doc.floor_a != doc.floor_b){\n    // delete connections between floors\n  \temit( [doc.buid, doc.floor_a], meta.id );\n    \temit( [doc.buid, doc.floor_b], meta.id );\n  }else if( doc.floor_a && doc.floor_b && doc.floor_a == doc.floor_b){\n    // connections on the same floor\n    \temit( [doc.buid, doc.floor_a], meta.id );\n  }\n}"
						},
						"all_by_buid": {
							"map": "function (doc, meta) {\n  if( doc.buid )\n    // delete pois & floor & building & connection\n  \temit( doc.buid, meta.id);\n  \n}"
						},
						"building_all_by_owner": {
							"map": "function (doc, meta) {\n  if(!doc.puid && !doc.floor_number && !doc.edge_type && doc.buid && doc.owner_id) {\n    emit(doc.owner_id, meta.id);\n    \n    if(doc.co_owners) {\n      for (var i = 0; i < doc.co_owners.length; i++) {\n        if (doc.co_owners[i] != doc.owner_id) {\n           emit(doc.co_owners[i], meta.id);\n        }\n      }\n    }\n    \n  }\n}"
						},
						"buildings_all_coordinates": {
							"map": "function (doc, meta) {\n  emit(meta.id, null);\n}"
						},
						"building_all_by_bucode_by_owner": {
							"map": "function (doc, meta) {\n  if (doc.buid && doc.bucode && doc.owner_id) {\n    emit([doc.bucode, doc.owner_id], null);\n  }\n}"
						},
						"building_all_by_bucode": {
							"map": "function (doc, meta) {\n  if (doc.buid && doc.bucode) {\n  \temit(doc.bucode, null);\n  }\n}"
						},
						"connection_by_buid_all_floors": {
							"map": "function (doc, meta) {\n  if( doc.buid && doc.cuid && doc.floor_a && doc.floor_b)\n      emit(doc.buid, doc);\n}"
						},
						"cuid_all_by_owner": {
							"map": "function (doc, meta) {\n  if (!doc.puid && !doc.floor_number && !doc.edge_type && doc.cuid && doc.owner_id){\n    emit( doc.owner_id, meta.id);\n  }\n}"
						},
						"get_campus": {
							"map": "function (doc, meta) {\n  if(doc.cuid && doc.owner_id )\n  \temit(meta.id, doc.cuid);\n}"
						},
						"all_pois_types": {
							"map": "function (doc, meta) {\n  if (doc.poistypeid && doc.owner_id && doc.types && !doc.buid) {\n  \temit(doc.owner_id, meta.id);\n  }\n}"
						}
					}
}
 it  returns nothing and seems to be incorrect.
Do you have the correct one?

**Comment by m6amiri** [comment]
@anyplaceucy could you help me, please

**Comment by Costantinos** [comment]
Hello,

All the view documents and the script for creating the views can be found under the [anyplace/server/anyplace_views/](https://github.com/dmsl/anyplace/tree/master/server/anyplace_views).
