### ISSUE TITLE
Something went wrong while attempting to connect the two POIs.

### ISSUE THREAD

**Issue by shantanubanerjee** [dmsl/anyplace#199]
I am not able to connect two poi and every time it shows exception.

> [info] application - LPLogger::Info:: AnyplaceMapping::connectionAdd(): {"username":"username","password":"password","owner_id":"101907354270118978517_google","pois_a":"poi_d9622d85-114b-4130-b05a-ed421332c24c","floor_a":"3","buid_a":"building_b487af41-28a1-44dd-ac62-87fda274b13d_1518701475819","buid":"building_b487af41-28a1-44dd-ac62-87fda274b13d_1518701475819","pois_b":"poi_880c2d27-da5d-4522-9ec6-4c7f664de372","floor_b":"3","buid_b":"building_b487af41-28a1-44dd-ac62-87fda274b13d_1518701475819","is_published":"true","edge_type":"hallway","access_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6ImUyNzY3MWQ3M2EyNjA1Y2NkNDU0NDEzYzRjOTRlMjViM2Y2NmNkZWEifQ.eyJhenAiOiI1ODc1MDA3MjM5NzEtc2k4czRxcWF0OXY1ZWZnZW1uZWJpaHBpM3FlOW9ubHAuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiI1ODc1MDA3MjM5NzEtc2k4czRxcWF0OXY1ZWZnZW1uZWJpaHBpM3FlOW9ubHAuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMDE5MDczNTQyNzAxMTg5Nzg1MTciLCJlbWFpbCI6InNoYW50YW51YmFuZXJqZWU3NUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXRfaGFzaCI6IkJqRkJubVVnaUdIeHUyY0kzZHBpWUEiLCJleHAiOjE1MTg3MDUwMzcsImlzcyI6ImFjY291bnRzLmdvb2dsZS5jb20iLCJqdGkiOiI4OGY2ZGQwOTM4ZDhmZTgyYzc2MDgwMDlkMjI4MDkxMWJmOTY4NDIzIiwiaWF0IjoxNTE4NzAxNDM3fQ.RKHR4-xdjBtoEr_upIwPHpd7urmwEgImRr0Ro3arKeJBgAsJvHHtaQvb-nFOFAwcS2XgNgGz0ZDhRJLCr-1JSJQHOaKQKHSUVIbNN4bqFVMCC6B-RQ_mt_OEvqthX7hYLF3Vr0pcnmfBhW37l0AAC7SNP0LETlvjGMSNMFf9_B5ZeMnOBpczoRpv6y6KZqvjN_m0Xv9lv08vfnvn52-_tAttdV_eygsuy5mtVxllR6aI4iDejyjM6SibQQvh7p7663d5QSvLKMA_w-cGKqtsfzMyUQhTB9YmXoGwy55E5p3u4vbgsUanbCaR6YZYgkKQDn6J62pEcH3gTxJPRomAZg"}
> [error] p.c.s.n.PlayDefaultUpstreamHandler - Cannot invoke the action
> java.lang.NullPointerException: null
> 	at db_models.Connection.getId(Connection.scala:96) ~[classes/:na]
> 	at controllers.AnyplaceMapping$$anonfun$connectionAdd$1.apply(AnyplaceMapping.scala:1317) ~[classes/:na]
> 	at controllers.AnyplaceMapping$$anonfun$connectionAdd$1.apply(AnyplaceMapping.scala:1278) ~[classes/:na]
> 	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:408) ~[play_2.11-2.4.2.jar:2.4.2]
> 	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:407) ~[play_2.11-2.4.2.jar:2.4.2]
> 	at play.api.mvc.Action$.invokeBlock(Action.scala:533) ~[play_2.11-2.4.2.jar:2.4.2]
> 	at play.api.mvc.Action$.invokeBlock(Action.scala:530) ~[play_2.11-2.4.2.jar:2.4.2]
> 	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:493) ~[play_2.11-2.4.2.jar:2.4.2]
> 	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[play_2.11-2.4.2.jar:2.4.2]
> 	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[play_2.11-2.4.2.jar:2.4.2]
> [error] application - 
> 
> ! @77261o76j - Internal server error, for (POST) [/anyplace/mapping/connection/add] ->
>  
> play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[NullPointerException: null]]
> 	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.2.jar:2.4.2]
> 	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11-2.4.2.jar:2.4.2]
> 	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [play_2.11-2.4.2.jar:2.4.2]
> 	at play.core.j.JavaGlobalSettingsAdapter.play$core$j$JavaGlobalSettingsAdapter$$super$onError(JavaGlobalSettingsAdapter.scala:36) [play_2.11-2.4.2.jar:2.4.2]
> 	at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onError$2.apply(JavaGlobalSettingsAdapter.scala:36) [play_2.11-2.4.2.jar:2.4.2]
> 	at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onError$2.apply(JavaGlobalSettingsAdapter.scala:36) [play_2.11-2.4.2.jar:2.4.2]
> 	at scala.Option.getOrElse(Option.scala:121) [scala-library-2.11.7.jar:na]
> 	at play.core.j.JavaGlobalSettingsAdapter.onError(JavaGlobalSettingsAdapter.scala:36) [play_2.11-2.4.2.jar:2.4.2]
> 	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [play_2.11-2.4.2.jar:2.4.2]
> 	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:273) [play-netty-server_2.11-2.4.2.jar:2.4.2]
> Caused by: **java.lang.NullPointerException: null**
> 	at db_models.Connection.getId(Connection.scala:96) ~[classes/:na]
> 	at controllers.AnyplaceMapping$$anonfun$connectionAdd$1.apply(AnyplaceMapping.scala:1317) ~[classes/:na]
> 	at controllers.AnyplaceMapping$$anonfun$connectionAdd$1.apply(AnyplaceMapping.scala:1278) ~[classes/:na]
> 	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:408) ~[play_2.11-2.4.2.jar:2.4.2]
> 	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:407) ~[play_2.11-2.4.2.jar:2.4.2]
> 	at play.api.mvc.Action$.invokeBlock(Action.scala:533) ~[play_2.11-2.4.2.jar:2.4.2]
> 	at play.api.mvc.Action$.invokeBlock(Action.scala:530) ~[play_2.11-2.4.2.jar:2.4.2]
> 	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:493) ~[play_2.11-2.4.2.jar:2.4.2]
> 	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[play_2.11-2.4.2.jar:2.4.2]
> 	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[play_2.11-2.4.2.jar:2.4.2]

*java.lang.NullPointerException: null inside Connection.scala:96.

Could you please help me to solve this.

**Comment by thedaini** [comment]
I'm having the same issue, has a resolution been found?

**Comment by anyplaceucy** [comment]
Also fixed in v3.1

**Comment by sreejith-ms** [comment]
@anyplaceucy what about the binaries? does that updated?

**Comment by thedaini** [comment]
@Costantinos Can you update the server binaries with the latest stable build with this fix?  Thank you.

**Comment by Costantinos** [comment]
Hello,

We will have everything up to date soon. I will update the binaries asap.
