### ISSUE TITLE
Log file in Navigator mode

### ISSUE THREAD

**Issue by bendata61** [dmsl/anyplace#2]
I have been able to locate the rssi log file in logger mode, but have not been able to find any similar log/output file in Navigator mode where the lat/lon of the user's location can be viewed on an Android phone. 

Many thanks

**Comment by constambeys** [comment]
Hello bendata61

The navigator mode does not output log files. It uses radiomap files that are
generated by the server based on the log files. The logger has an Upload RSS Log option
that uploads the log file to the server. The navigator then downloads the generated radiomap file.

**Comment by bendata61** [comment]
Thanks for the prompt reply. 

I am currently more interested in accessing the lat/lon location of the user in the Navigator mode, as I would like to evaluate the app's accuracy to a ground truth. Is there a way to access this information?

Many thanks

**Comment by constambeys** [comment]
I suggest that you modify the onNewLocation(final LatLng pos) method in UnifiedNavigationActivity. This is a callback method that updates the navigator for new wifi locations

**Comment by bendata61** [comment]
Thanks for the help, I have been able to modify the method as stated above to view the lat/lon positions in Navigator.
