### ISSUE TITLE
Is this a offline solution or online solution?

### ISSUE THREAD

**Issue by shwetankb11** [dmsl/anyplace#201]
Hi there,

I am testing this application and when I turn off the device location and internet connectivity, the application(Android) does not give me directions.

**Comment by anyplaceucy** [comment]
We are working on release 3.1 that should replace the problems of the existing 2.8 version. Version 3.1 is founded on the 3.0 codebase that brings many new improvements. Please stay tuned for the update.

**Comment by shwetankb11** [comment]
Ohk, Thanks for the quick response
Can you please tell me that is this possible to run this in offline mode or I need permanent internet connectivity.

**Comment by anyplaceucy** [comment]
Yes once the radiomap structures are downloaded to the Android App, the app operates without internet connectivity
