### ISSUE TITLE
Running server doesnt create radio maps

### ISSUE THREAD

**Issue by hashmedia1** [dmsl/anyplace#203]
Hello 

 I am running server on ubuntu when i am submiting rss log file.. server says Radio Map entry was not saved in database![Possible duplicate] and after that it stuck at rss-log
writing radio map to files again refreshing the building it is not downloading the rss log file 

Please help

Thanks

**Comment by anyplaceucy** [comment]
We are aware of the problem that is already fixed in v3.1 soon to substitute v2.8. Please be patient. Our plan is to release by the end of the week.

Demetris

**Comment by hashmedia1** [comment]
Can you please me suggest previous version in which this was running perfectly ??
