### ISSUE TITLE
Something went wrong while fetching buildings

### ISSUE THREAD

**Issue by thedaini** [dmsl/anyplace#208]
I'm setting up an Anyplace server and I can access viewer, architect, etc. from localhost on the server.  However, when I try to access the viewer externally the page loads but I receive an error "Something went wrong while fetching buildings.".  

Developer tools gives this:
angular.js:9893 OPTIONS http://localhost:9000/anyplace/mapping/building/all net::ERR_CONNECTION_REFUSED

Need assistant to determine if this is a permission issue with my server instance or if it's code related.

**Comment by thedaini** [comment]
You need you change the following in the AnyplaceAPI.js files for architect, viewer, and viewer_campus.
From:
AnyplaceAPI.FULL_SERVER = "http://localhost:9000/anyplace";
To:
AnyplaceAPI.FULL_SERVER = "http://_yourservername_/anyplace";
Then build those three directories using the instructions for the grunt build of architect.  
Finally, build the entire project from the main directory using the sbt command then the dist command.  The binaries produced will be pointed to your server.

**Comment by dikobagda** [comment]
Hai @thedaini 

I successfully compiled anyplace on my localhost, but when i start http://localhost:9000/viewer, i got an error message like this. 
 
<img width="1439" alt="screen shot 2018-03-05 at 5 25 14 pm" src="https://user-images.githubusercontent.com/1335894/36970551-94bc8880-209b-11e8-8bae-e9e1d8dc2a22.png">


i also check my AnyplaceAPI.FULL_SERVER running on http://localhost:9000/anyplace

Need your help, thanks.

**Comment by kayhanbaysal** [comment]
I have same error message.
