### ISSUE TITLE
Anyplace v3.2 Testers needed - we need your help!

### ISSUE THREAD

**Issue by anyplaceucy** [dmsl/anyplace#212]
The Anyplace team would like to invite you taking part in the extensive testing of v3.2 (soon to replace the deprecated v2.8) version. To take part in the testing just visit the following URLs:

Architect: https://ap.cs.ucy.ac.cy/architect/
Viewer: https://ap.cs.ucy.ac.cy/viewer/
API: https://ap.cs.ucy.ac.cy/developers/
Android: Download Anyplace 2.4 from the play store (https://play.google.com/store/apps/details?id=com.dmsl.anyplace). Then carry out the following change: Settings -> Preferences -> Anyplace Server IP Address -> type in: https://ap.cs.ucy.ac.cy 

INFO: Remember that https://ap.cs.ucy.ac.cy/ is a testing server, so whatever changes or updates you carry out at the above URL will not affect the Anyplace PUBLIC server database (https://anyplace.cs.ucy.ac.cy/). So freely do any deletions / updates / insertions you want!

What is new in 3.2?
- Lots of bug fixes and stability improvements
- The Fingerprint Management Studio (FMS): Fingerprint Management Studio (FMS) is an indoor signal management studio that provides a uniform platform to: (i) manage the collection of location-dependent sensor readings (i.e., fingerprints) in indoor environments; (ii) estimate the localization accuracy based on the collected fingerprints; and (iii) assess Wi-Fi coverage and data rates. FMS comprises of the following components: (i) CSM (Crowd Signal Map), which is a map-based visual management environment to orchestrate the crowdsourcing effort of indoor signals for ethical benefit; (ii) ACCES (Accuracy Estimation), which en- ables the qualitative assessment of localization accuracy before deploying the localization service (i.e., in the laboratory as opposed to the field) using Gaussian Processes Regression and the Cramer-Rao Lower Bound (CRLB); and (iii) WS (Wi-Fi Surveying), which enables the qualitative assessment of Wi-Fi coverage using the signals collected by crowdsourcers.

**Comment by anyplaceucy** [comment]
We will of course also appreciate if somebody can shot an installation video and post a video here. More: "Anyplace v3.2 for administrators"

**Comment by dikobagda** [comment]
I installed from binaries and source code. but i hv this problem. 

What java version suitable for anyplace ?

<img width="1211" alt="screen shot 2018-03-06 at 8 03 02 pm" src="https://user-images.githubusercontent.com/1335894/37033703-6e3e2f4a-2179-11e8-8175-39d8308ed245.png">

**Comment by Costantinos** [comment]
Hello,

You need to create a cluster with couchbase servers and run the provided script to create the views.

**Comment by dikobagda** [comment]
Hello @Costantinos

I successfully installed, and also success connected to couchbase. i tried to add building on architect and success to insert into couchbase.

but when i launch viewer or architect page this message is coming up.

<img width="1435" alt="screen shot 2018-03-06 at 9 36 20 pm" src="https://user-images.githubusercontent.com/1335894/37038301-01da9682-2187-11e8-876a-6d9a1bf82a6b.png">

<img width="1281" alt="screen shot 2018-03-06 at 9 38 17 pm" src="https://user-images.githubusercontent.com/1335894/37038358-26827e82-2187-11e8-94b5-b8f30c6bd137.png">

<img width="1418" alt="screen shot 2018-03-06 at 9 41 23 pm" src="https://user-images.githubusercontent.com/1335894/37038377-3864db22-2187-11e8-8ced-94b94d041574.png">

**Comment by Costantinos** [comment]
What version of Couchbase are using?

**Comment by dikobagda** [comment]
i am using couchbase Version 5.0.1 (5.0.1-5003)
<img width="284" alt="screen shot 2018-03-06 at 9 53 32 pm" src="https://user-images.githubusercontent.com/1335894/37038969-dca86824-2188-11e8-9ff4-2bfcc18815cb.png">

**Comment by Costantinos** [comment]
Due to an update of Couchbase 5.0 you need to create a user with username the bucket name (described in [README.md](https://github.com/dmsl/anyplace/tree/master/server)).  If you continue to have additional problems try to download the latest version.

**Comment by dikobagda** [comment]
ok, Thank you very much, appreciate it. @Costantinos
