### ISSUE TITLE
Error fetching floor plan. [ Service Error: Bad Request ]

### ISSUE THREAD

**Issue by thedaini** [dmsl/anyplace#215]
I receive the above error when trying to select a building in the Android app after pointing it to the anyplace server I set up.  The app successfully retrieves the list of buildings on my server but cannot retrieve the floorplans.  All floorplans, buildings, POIs, routing, etc. were added using the same account.

Are there additional set up/compile steps I'm missing?  Not sure what's up with the username and password values.

Here's my console log:
```
[info] application - LPLogger::Info:: AnyplaceMapping::buildingAll(): {"username":"username","password":"pass"}
{"name":" ??:"}
 ??:
[info] application - LPLogger::Info:: AnyplaceMapping::floorAll(): {"username":"username","password":"pass","buid":"building_blahblahblahblahblah"}
couchbase results: 2
[info] application - LPLogger::Info:: AnyplaceMapping::serveFloorPlanTilesZip(): {"username":"username","password":"pass"}
[info] application - LPLogger::Info:: requested: floor_plans\building_blahblahblahblahblah\fl_1\static_tiles\tiles_archive.zip
```

**Comment by Costantinos** [comment]
Hello,

The URL of the server should be using only https. Does your server support https?

**Comment by thedaini** [comment]
Yes, but when I switch over to ssl with a cert I get
```
Error fetching buildings. [ java.security.cert.CertPathValidatorException: Trust anchor for certification path not found. ]
```
Do I have to use lets-encrypt as my cert provider?

**Comment by thedaini** [comment]
Ok, I have successfully configured a signed https on my server but I still get the same error:
```
Error fetching floor plan. [ Service Error: Bad Request ]
```

**Comment by thedaini** [comment]
Packet sniffed the android POST and response.

Response says 
```
"Requested floor plan does not exist or cannot be read! (1)", "status_code":400,"status":"error"
```

**Comment by cosmomill** [comment]
Hello,

same problem here. I use the precompiled [binaries](https://anyplace.cs.ucy.ac.cy/downloads/anyplace_v3.zip) on Windows. After some further debugging I found that `tiles_archive.zip` in `floor_plans` for the building in question is missing.

**Comment by MondayDev** [comment]
I have this issue using your server. There seems to be some change in the app that isn't aligned with the web service call for getting the floor plans. I have the latest version from GITHUB

**Comment by anyplaceucy** [comment]
You need SSL on your server + on Android you need to provide the server IP through the interface (for the public Anyplace service the URL is https://ap.cs.ucy.ac.cy).

Follow the instructions on Github for setting up SSL on your server (https://github.com/dmsl/anyplace/tree/master/server).

**Comment by westlakem** [comment]
@anyplaceucy @thedaini I'm running into the same issue.  

![image](https://user-images.githubusercontent.com/4505074/38823052-53723e30-4173-11e8-9586-1798dab9f7c9.png)

I'm over HTTPS but i'm using the self-signed AWS certificate at the moment and I don't know if that's causing an issue or not.
