### ISSUE TITLE
missing views of heatmap

### ISSUE THREAD

**Issue by jhzzzz** [dmsl/anyplace#216]
Hi, 

These functions include getRadioHeatmapByBuildingFloorAverage, getRadioHeatmapByBuildingFloorAverage1 ~ 3 in CouchbaseDatasource.scala use the view query of heatmaps, but it was missing from the anyplace_views, is there something wrong?

val viewQuery = ViewQuery.from("heatmaps", "heatmap_by_floor_building_level_1").startKey(startkey).endKey(endkey).group(true).reduce(true).inclusiveEnd(true)

**Comment by Costantinos** [comment]
The views creation script and json documents have been updated.

**Comment by dharmeshkumar** [comment]
Hi,

The same kind of issue is going on with getFingerPrintsTime function of  CouchbaseDatasource.scala . It is using "timestamp_by_floor_building" view of heatmap design but this view is somehow missing from the heatmap design.

val viewQuery = ViewQuery.from("heatmaps", "timestamp_by_floor_building").startKey(startkey).endKey(endkey).group(true)
