### ISSUE TITLE
https://anyplace.rayzit.com/ is down 

### ISSUE THREAD

**Issue by butbut1314** [dmsl/anyplace#222]
https://anyplace.rayzit.com/ is down
ERR_CONNECTION_TIMED_OUT

**Comment by constambeys** [comment]
Yes https://anyplace.rayzit.com/ uses the old backend. The new backend is on https://ap.cs.ucy.ac.cy. Android app will be updated soon.

**Comment by edmundhei** [comment]
I can get the building now but can't load the floor plan

**Comment by butbut1314** [comment]
I can get the building to load now. But the building floor won't load. Error fetching floor plan: Service error  not found

**Comment by constambeys** [comment]
check version 2.5

**Comment by Alexandratz** [comment]
Good morning,
Is there any issue with  https://ap.cs.ucy.ac.cy or the problem is on my side? Actually, plotting Navigation is taking forever.

Thank you in advance for your assistance.

**Comment by anyplaceucy** [comment]
It probably has to do with the location settings in your browser (it might also have to do with Google Outdoor navigation - e.g., if the building you asked for a route is in a different continent, it will take considerably more time).

There will be btw an update on 3.3 later today, but it has not to do anything with navigation.
