### ISSUE TITLE
Self-hosted instance doesn't connect/use own Database

### ISSUE THREAD

**Issue by sbpipb** [dmsl/anyplace#225]
What I am trying to accomplish is setup an own Anyplace Server instance on my server.

I used the Binary version **https://github.com/dmsl/anyplace/tree/master/server#setupconfiguration**

I was able to setup my own hosted Anyplace application by following instructions for [Admin](https://github.com/dmsl/anyplace/tree/master/server#anyplace-v3x-for-administrators) 
but it seems that the data (buildings, POI) that I am seeing on my end is the same data from the [demo application ](https://anyplace.cs.ucy.ac.cy/viewer/).  What I would like to accomplish is host my own instance with my own data only..  Is this even possible? 

Next step is to setup Anyplace on my local environment. Here's to comparing setting up Anyplace for Admins vs Developers. 

Here's the logs as well when I ran Anyplace
`root@server:~/anyplace_v3-2.0/bin# ./anyplace_v3
[warn] application - Logger configuration in conf files is deprecated and has no effect. Use a logback configuration file instead.
[info] p.a.l.c.ActorSystemProvider - Starting application default Akka system: application
[info] application - Global::onStart():: AnyPlace Application started
[info] application - Trying to connect to: http://myownhost:8091 bucket[bucketname] password: password[info] play.api.Play - Application started (Prod)
[info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
`

**Comment by sbpipb** [comment]
i think the issue isn't database related but the host being connected by the Viewer application is hard-coded, connecting to localhost:9000


File: 
server/public/anyplace_viewer/scripts/AnyplaceAPI.js
 
`AnyplaceAPI.FULL_SERVER = "http://localhost:9000/anyplace";`

**Comment by Costantinos** [comment]
Hello,

What is the problem? From the log its  seems that everything is running as expected. If you want to set it up on a public server you need to change the server address on the AnyplaceAPI.js under viewer/campus/architect directory and rebuild them using the instructions provided for each component (e.g [anyplace_viewer](https://github.com/dmsl/anyplace/tree/master/server/public/anyplace_viewer))

**Comment by sbpipb** [comment]
Would it be possible to include this in the documentation of _setting up your own hosted application_? 

> If you want to set it up on a public server you need to change the server address on the AnyplaceAPI.js under viewer/campus/architect directory and rebuild them using the instructions provided for each component (e.g anyplace_viewer)
