### ISSUE TITLE
Radio Map File is not creating

### ISSUE THREAD

**Issue by hashmedia1** [dmsl/anyplace#229]
Hello I am uploading RSS LOG many times but radio map is not creating... in building/floor directory in radiomap_frozen only empty rss_log file is there.. no other file... in radiomap_raw directory uploaded rss log files are there...
when i upload the file it shows rss-log
[info] application - LPLogger::Info:: total fetched: 0

Please help

**Comment by Costantinos** [comment]
Hello,

We are currently working to fix this particular issue. We will have a new version very soon.

**Comment by hashmedia1** [comment]
In any of the previous version it is working ??? then please tell me the older versions... i need it very urgent...

**Comment by Costantinos** [comment]
Hello,

The new version has been posted.
