### ISSUE TITLE
Google Api key

### ISSUE THREAD

**Issue by yardensw** [dmsl/anyplace#238]
According to "New pricing and product changes will go into effect starting June 11, 2018. For more information."
because we are using google api in this platform for map and location.. what should we do?
now it will cost money?

i already have google api key int manifest but it still not recognize the com.google.android.gms.maps.model

thanks,
Yarden

**Comment by anyplaceucy** [comment]
We are working with OpenStreetMap integration and will post updates soon.

**Comment by yardensw** [comment]
Thanks for the quick reply!
I would like to know if this means that in the meantime we can not work with the existing version in github until the update will be released?
If so, I'd love to know when the update will come out 
If not, I'd also love to know how to fix it temporarily until the update will be released

Thank you!!!!
Yarden

**Comment by anyplaceucy** [comment]
You have to wait a bit more until the update is available. The Github version 3.3 should remain operational until June 11, 2018.

If you want to check out Anyplace 3.4 (integrated over OpenstreetMaps), check https://ap-dev.cs.ucy.ac.cy/viewer. We expect to have v3.4 fully adapted, tested and released by the end of this month (May 2018).

**Comment by gorn** [comment]
Any news on this?

**Comment by anyplaceucy** [comment]
Anyplace doesn't rely on Google Maps any more (as of 3.4) as it already has several tile providers integrated. When Google blocks access, Anyplace will still operate with Open Street Maps or Carto tiles. The only thing that we will miss when Google departs is the "outdoor navigation" edges. The in-building edges will still work correctly.

**Comment by bharti112** [comment]
Can anyone explain how anyplace is not dependent on Google Maps any more? I can still see Google maps integrated in anyplace architect and viewer code.
How to make it use Open Street Maps and not Google Maps?

**Comment by kapilsaini** [comment]
> Anyplace doesn't rely on Google Maps any more (as of 3.4) as it already has several tile providers integrated. When Google blocks access, Anyplace will still operate with Open Street Maps or Carto tiles. The only thing that we will miss when Google departs is the "outdoor navigation" edges. The in-building edges will still work correctly.

Hi, I still see call to Google maps api being made from index.html in architect 
"https://maps.googleapis.com/maps/api/js?key"...so can you explain how anyplace have moved away from google maps ?

**Comment by anyplaceucy** [comment]
We already mentioned that as long as Google Maps doesn't ban access, we continue to use it on the public anyplace service clone. Individual installations have the choice to disable it. 

There are actually some benefits of continuing the use of Google Maps: We have tiles up to zoom level "20" (with good detail), we have outdoor navigation.

**Comment by gorn** [comment]
OpenStreet map has max zoom level 20 and in many cases it has much more details for oudoor navigation. At least in Europe I have never seen a place where googlemaps would be better for outdoor.
