### ISSUE TITLE
Compilation error Symbol Class R Cannot be found

### ISSUE THREAD

**Issue by GoldenWings** [dmsl/anyplace#25]
When compiling the project with android studio i receive the following error:
Error:(40, 25) java: cannot find symbol
  symbol:   class R
  location: package com.dmsl.anyplace

Any point would be appreciated.
Thanks.

**Comment by constambeys** [comment]
Check that you have the latest source code and update sdk and android studio to the latest version 2.1.1. Then in Android Studio click Open an existing Android Studio project and select the android folder. Then click the icon Sync Project with Gradle Files and in the event log it should write Gradle build finished in X seconds

**Comment by GoldenWings** [comment]
Thank you very mush those steps are exactly the steps to solve the issue.
