### ISSUE TITLE
Map is not loading in Android source

### ISSUE THREAD

**Issue by harshitlalpura** [dmsl/anyplace#26]
Hello.

When I deploy android source in Android studio then Google Map is not loading in Logger or Navigator. Please help me. In logger no option of start recording is comming. Waiting for  your reply.

Thanks

**Comment by constambeys** [comment]
To use the Google Maps Android API, you must register your app project on the Google Developers Console and get a Google API key which you can add to your app. 
Check https://developers.google.com/maps/documentation/android-api/signup#release-cert
Insert the key at the last line in Anyplace/AndroidManifest.xml

**Comment by harshitlalpura** [comment]
Thanks @constambeys it got solved...
