### ISSUE TITLE
XXE in GMapV2Direction.java via Man-in-the-Middle (MitM)

### ISSUE THREAD

**Issue by ProDigySML** [dmsl/anyplace#263]
# The Issue
An XML External Entity attack is a type of attack against an application that parses XML input. This attack occurs when XML input containing a reference to an external entity is processed by a weakly configured XML parser. This attack may lead to the disclosure of confidential data, denial of service, server side request forgery, port scanning from the perspective of the machine where the parser is located, and other system impacts.

# Where the Issue Occurred
The following code snippets display the usage of `DocumentBuilderFactory` without securely disabling entities:

https://github.com/dmsl/anyplace/blob/80359b4d0546d383e2cb0dfd66127c3bbb82b846/android/Anyplace/src/com/dmsl/anyplace/googleapi/GMapV2Direction.java#L91

An attacker can Man-in-the-Middle (MitM) the HTTP call to the URL below:

https://github.com/dmsl/anyplace/blob/80359b4d0546d383e2cb0dfd66127c3bbb82b846/android/Anyplace/src/com/dmsl/anyplace/googleapi/GMapV2Direction.java#L76

**Comment by constambeys** [comment]
Endpoint was made secure using https in v2.5.2

**Comment by anyplaceucy** [comment]
That's great @constambeys, thanks.
