### ISSUE TITLE
In Anyplace Logger Floor Plan is moving

### ISSUE THREAD

**Issue by harshitlalpura** [dmsl/anyplace#27]
Hello.

When i run anyplace logger android then floor plan is moving when I drag or zoom in the map its not coming fixed please help me..

Thanks.

**Comment by constambeys** [comment]
The floor plan is moving when you drag or zoom the map. Is this for a specific building?

**Comment by harshitlalpura** [comment]
it happening for all the building plans i added. When I zoom building floor plan becomes small than actual building in android and when I drag it moves from the fixed place I decided from the architecture..

**Comment by anyplaceucy** [comment]
Please check if related to https://github.com/dmsl/anyplace/issues/3 and reopen if necessary
