### ISSUE TITLE
Show specific pushpin only

### ISSUE THREAD

**Issue by GoldenWings** [dmsl/anyplace#28]
Can i hide all the buildings and show only my building in android?

**Comment by constambeys** [comment]
No but you can change the source code in Anyplace Cache loadWorldBuildings.

**Comment by GoldenWings** [comment]
And remove all the buildings except the building that its id is my buid right ? 
I've tried that but it removes other buildings from the list thats exists in the select building page not the pushpins from the map of other buildings any guidance please ?

**Comment by constambeys** [comment]
Yes remove all the building except the building with your buid. 
Try to clear cache using the android's clear cache option

**Comment by GoldenWings** [comment]
Thanks for your reply i will give it a try, if you may help in my other issue which is critical and not expected, when i try to plot a navigation route to destination it says there is no path exists from your current location to POI selected  i already a new issue on the subject, i appreciate any thoughts.
Thanks for your time.

**Comment by constambeys** [comment]
I don't know about this error. I guess it is not throw by the android app. Check again the architect settings and verify they are correct. Wait for Kyriako's answer
