### ISSUE TITLE
With Logging something is wrong.

### ISSUE THREAD

**Issue by harshitlalpura** [dmsl/anyplace#29]
when i am recording wifi in logger part sampling is doing very fast not like shown in video on your website. And some time i have taken the sample of all floors then only few of the samples are coming on radiomap. and sometimes even I take sample of other part of that  floor again then also after uploading rss logs it not showing new radio maps... how much time it will take to update radio maps on your server... can you please tell me the best combination of walking sensitivity and time interval of sample. and how fast should i walk while taking sample... please help

**Comment by harshitlalpura** [comment]
my heatmap is like this..
![13334563_10204922507700944_1262147876_o](https://cloud.githubusercontent.com/assets/10074963/15777213/2d088632-29ab-11e6-9259-9018a47da967.png)

**Comment by dzeina** [comment]
Try the Wiki Page: https://github.com/dmsl/anyplace/wiki/Best-Practices-for-producing-WiFi-Radiomap-In-Anyplace-Android
