### ISSUE TITLE
current location not correct 

### ISSUE THREAD

**Issue by elenakalimera** [dmsl/anyplace#291]
I am not able to find my current location on top of the floorplan map and navigate between POIs inside the building using Anyplace Navigator, does it depend on how correctly should we add the building and the floorplan at Architect?
And if it depends on how to add the floorplan at Architect, how can we get the correct location from the beginning and put the floorplan in the right direction?

**Comment by anyplaceucy** [comment]
Please check the 4 posts under Wiki https://github.com/dmsl/anyplace/wiki
