### ISSUE TITLE
What is the significance of MAC addresses obtained after uploading RSS log in Anyplace logger in mobile application 

### ISSUE THREAD

**Issue by BHARGAVISUDHAKAR** [dmsl/anyplace#298]
**Question 1.** 
[](https://drive.google.com/file/d/1mErqs611H0IFn-A04Y1wf5PF1qr-d0op/view?usp=sharing)

Please find the above link for the picture of the radio map generated after uploading the RSS log in Anyplace logger. 

What is the meaning of the 'by MAC' addresses and the 'By manufacturer' options in the Wi-Fi coverage tab as highlighted in the above picture ?
Is it the list of all devices connected to the Wi-Fi network ?

**Question 2.** 
Also, is it possible to find the number of devices/people connected to the network in a room using AnyPlace ? Is it possible to live track the number of people/devices connected to the Wi-Fi network ?
If possible, please guide with the corresponding steps required to achieve the same. 

![Anyplace heat map](https://user-images.githubusercontent.com/51232568/58701445-7ffbec80-83d5-11e9-80ea-211a3e747809.JPG)
. 

Thank You

**Comment by kgeorgiou** [comment]
Answer to Question 1:
Those are the [MAC addresses](https://en.wikipedia.org/wiki/MAC_address) of the WiFi Access Points in the building, that were involved in the signal readings of the uploaded RSS Log.

Answer to Question 2:
Anyplace doesn't support such capabilities. Keep in mind the localization happens on the user's device and not on the server:
> The Privacy module enables smartphone users to calculate their location on their own device by downloading minimal parts of the stored Radiomap, “hiding” among k random AP areas.

Source: [Anyplace: A Crowdsourced Indoor Information Service](https://www.cs.ucy.ac.cy/~dzeina/papers/mdm15-anyplace-demo.pdf)

I hope this answers your questions :)
