### ISSUE TITLE
Security alert  Your app contains an unsafe unzipping pattern that may lead to a Path Traversal vulnerability. Please see this Google Help Center article to learn how to fix the issue.  Vulnerable locations:  com.dmsl.anyplace.utils.AndroidUtils.unzip Affects APK version 50.

### ISSUE THREAD

**Issue by anyplaceucy** [dmsl/anyplace#307]
Security alert

Your app contains an unsafe unzipping pattern that may lead to a Path Traversal vulnerability. Please see this Google Help Center article to learn how to fix the issue.

Vulnerable locations:

com.dmsl.anyplace.utils.AndroidUtils.unzip
Affects APK version 50.

FIX:
https://support.google.com/faqs/answer/9294009

**Comment by anyplaceucy** [comment]
@constambeys can you please patch this ?

**Comment by constambeys** [comment]
Patched

**Comment by anyplaceucy** [comment]
Thanks Timothee, can you please also post an update to the Play store?

**Comment by constambeys** [comment]
Updated to version 2.5.3
