### ISSUE TITLE
How many routers are needed  for good fingerprint ?

### ISSUE THREAD

**Issue by harshitlalpura** [dmsl/anyplace#31]
Hello,

I have 20 fixed routers in the area which i try to fingerprint but still accuracy is not good. Its upto 10-15 meter.. anyplace can achieve upto 2 meter. So more routers are good or less routers are good ? Please Help.

**Comment by constambeys** [comment]
More routers is better. However 20 routers are sufficient. Try collecting more fingerprints and use the same device for evaluation

**Comment by harshitlalpura** [comment]
yes but it will track other devices right? or it will track only those devices which were used to take fingerprint.??

**Comment by constambeys** [comment]
Yes it will track other devices but the device used for recording will be more accurate

**Comment by harshitlalpura** [comment]
i did the fingerprint with 4 routers but its not showing results accurate... so router is the reason or something else ? Please help.

**Comment by anyplaceucy** [comment]
There is a tutorial under WIKI.
