### ISSUE TITLE
Navigation routes not works

### ISSUE THREAD

**Issue by GoldenWings** [dmsl/anyplace#32]
I am using android and i've uploaded the floor maps and the radio maps and everything is set but when i try to navigate, it says no valid path exists from your current position to the selected POI .
Could any one please help me.
Thanks in advance.

**Comment by GoldenWings** [comment]
This is how my radio maps works
http://s32.postimg.org/cu59aye2t/Screenshot_20160614_011457.png

**Comment by anyplaceucy** [comment]
You forgot to include the edges between POIs. Toggle edge mode ON and then hit on any two POIs to create the paths across the building. Use the X-connectors to draw corners. See the below image for more details.

![image](https://cloud.githubusercontent.com/assets/19922199/16031768/b996dcc0-3207-11e6-8dc7-2c8431e0432b.png)

**Comment by GoldenWings** [comment]
Thank you for your nice reply, i got it now but what is the x-connectors?

**Comment by GoldenWings** [comment]
and why when i click on navigate it makes route between two flags the stairs or elevator and the destination i think it should draw route between my location to the destination not between flags right?

**Comment by anyplaceucy** [comment]
The X-connectors just allow you to create corners (i.e., these are hidden POIs with no description or name).
