### ISSUE TITLE
How to use the Campus Mode?

### ISSUE THREAD

**Issue by uncindoordev** [dmsl/anyplace#324]
From the context that we can actually hide other buildings in AnyPlace viewer by just using or creating a Campus but we can't find any intuitive way to do it. When we try to add a new Campus, an error says no building is selected but we selected our building(?).

Any help is very much appreciated. Thanks!

**Comment by uncindoordev** [comment]
**We got it. You actually have to load the page after adding buildings after that a selection of buildings you made will be shown in the Campus Mode.**

Another one, how can we use the URL or the Campus we made on the android app? We tried by changing the URL server but it wont work and still detects nearby POI buildings?

**Comment by anyplaceucy** [comment]
Displaying Campus mode in Android is currently not supported but will most probably supported in the future with the progress of the Anyplace Library in Anyplace 4.0 (released in June 2020)
