### ISSUE TITLE
Error connection to Couchbase: Passwords for bucket "anyplace" do not match

### ISSUE THREAD

**Issue by btelintelo** [dmsl/anyplace#335]
I am running the server locally.  Looks like Couchbase 5 got rid of bucket passwords.  Should anyplace be running a lower version or can it be updated for Couchbase 5?

**Comment by Paschalis** [comment]
Anyplace is using Couchbase 6.0, therefore there aren't any bucket passwords.
Try using instead an RBAC account to provide an extra layer of security to a bucket if that's what you desire.
It's the same thing with MySQL for example, when a particular user is created and is given access to a specific set of databases (buckets in our case).

Also try using our [docker](https://github.com/dmsl/anyplace/tree/develop/docker) deployment method (on the develop branch)  that automates everything in local scenarios and give us your feedback.
