### ISSUE TITLE
Is the API backend source available?

### ISSUE THREAD

**Issue by cmdr2** [dmsl/anyplace#34]
Hi there,

I was wondering whether the source code of the API backend is available? At the moment I see that the server is hosted at anyplace.rayzit.com, but is it possible to self-host this?

Thanks
~cmdr2

**Comment by GoldenWings** [comment]
I see that it is mentioned in the readme file but the source is not included, i believe its been taken down from being a part of the open source project?

**Comment by kgeorgiou** [comment]
Hello and thank you for your interest!

The team is currently preparing the backend codebase to be published on GitHub as soon as possible - I will notify you on this thread once the source code is pushed (also keep an eye on the Development branch for new updates.)

Meanwhile, we use [Play Framework](https://www.playframework.com/) for Anyplace Server and [Couchbase](http://www.couchbase.com/) as our datastore. If you have any questions on how those technologies empower Anyplace, please do ask!

**Comment by cmdr2** [comment]
Thanks, that's great news! Looking forward to it.

**Comment by kgeorgiou** [comment]
Hello @cmdr2 and @GoldenWings, the server is available [here](/dmsl/anyplace/blob/develop/server). 

Although, there's still work in progress in terms of documentation and the Couchbase views (required for the server to run) are yet to be published.

**Comment by mjcarroll** [comment]
Any update on when the Couchbase views will be available?

**Comment by harshitlalpura** [comment]
Any update on when the Couchbase views will be available?

**Comment by akpmp** [comment]
how to configure anyplace server for couchbase database.
please help me
