### ISSUE TITLE
Unable to access the corresponding address to download the required libraries

### ISSUE THREAD

**Issue by Sujiyi** [dmsl/anyplace#348]
[error] Server access Error: Unexpected end of file from server url=http://repo.typesafe.com/typesafe/ivy-releases/io.spray/spray-json_2.10/1.3.2/ivys/ivy.xml
[error] Server access Error: Unexpected end of file from server url=http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/io.spray/spray-json_2.10/1.3.2/ivys/ivy.xml
[error] SERVER ERROR: HTTPS Required url=http://repo1.maven.org/maven2/io/spray/spray-json_2.10/1.3.2/spray-json_2.10-1.3.2.pom
[error] Server access Error: Remote host terminated the handshake url=https://repo.typesafe.com/typesafe/releases/io/spray/spray-json_2.10/1.3.2/spray-json_2.10-1.3.2.pom
[warn] 	module not found: io.spray#spray-json_2.10;1.3.2
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/io.spray/spray-json_2.10/1.3.2/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/io.spray/spray-json_2.10/1.3.2/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\17812\.ivy2\local\io.spray\spray-json_2.10\1.3.2\ivys\ivy.xml
[warn] ==== local-preloaded-ivy: tried
[warn]   file:/C:/Users/17812/.sbt/preloaded/io.spray/spray-json_2.10/1.3.2/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:/C:/Users/17812/.sbt/preloaded/io/spray/spray-json_2.10/1.3.2/spray-json_2.10-1.3.2.pom
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/io/spray/spray-json_2.10/1.3.2/spray-json_2.10-1.3.2.pom
[warn] ==== Typesafe repository: tried
[warn]   https://repo.typesafe.com/typesafe/releases/io/spray/spray-json_2.10/1.3.2/spray-json_2.10-1.3.2.pom

How can i solve this problem？Is there any other way to get the required libraries？

**Comment by sbonzo** [comment]
Hi, I've the same issue and I'm stuck with this whithout creating my own server. Any solution?

**Comment by Paschalis** [comment]
Hi there.

There might be some warnings or even errors while SBT tries to download
dependencies.
Regardless, it is most likely that the build will eventually succeed.

We recently noticed an issue however with the SBT version, that is fixed if
we bump to the latest patch version.
I've pushed an update on develop and master branches.

Cheers,
Paschalis
