### ISSUE TITLE
docker anyplace base not available?

### ISSUE THREAD

**Issue by alibama** [dmsl/anyplace#349]
docker build anyplace-base/ -t anyplace-base

says it will be published in Docker Hub but i'm not sure it's there?

**Comment by Paschalis** [comment]
No, it is not there yet. We evaluate docker on internal projects, and we will publish it at some point in the future.
But you can still use the image! To create the base image use the comment you mentioned above:
`docker build anyplace-base/ -t anyplace-base`

Also consult the [README](https://github.com/dmsl/anyplace/tree/master/docker) .

**Comment by dzeina** [comment]
Amazing transformation on the master branch ... congrats !

 I am not sure I understand the reason gradle / maven has this requirement... maybe we can create a hard link like reference ? We have to check if github supports this  

Demetris Zeinalipour 
www.cs.ucy.ac.cy/~dzeina
