### ISSUE TITLE
There is no file  in ./couchbase/initialize.sh

### ISSUE THREAD

**Issue by amiour-billel** [dmsl/anyplace#350]
after launching the container with docker-compose and when launching the **./post_install.sh** script, I got the following message: `./post_install.sh: line 16: ./couchbase/initialize.sh: No such file or directory`
the file does not really exist !!

**Comment by sbonzo** [comment]
Hi everyone, I tried the docker version too with the same problem and only if I  set manually the couchbase instance seems to work but with several error.
Any solution?

**Comment by Paschalis** [comment]
Hi all,

Some files were missing from the public repo, and there are also some issues on the configuration files.
I'm working on it, and will post an update at some point.

Cheers!

**Comment by Paschalis** [comment]
Hi @amiour-billel  @sbonzo ,

Thanks for spotting this. I have updated the code on the **develop branch** (9d90a930) to address this.

Apart from 2 missing scripts, I've updated some issues on the configuration files
(.env, conf/application.conf), and tuned some defaults.
It should be able to run on a 2GB docker environment (maybe even 1GB).
I've added a bit more info on  READMEs.

I've tested it and this works well on a clean installation on:
    - a Linux Ubuntu server
    - a macOS Catalina notebook

Please make sure you delete any old images before trying the updated one.

**Comment by amiour-billel** [comment]
It work 👍  thank you @Paschalis

**Comment by Paschalis** [comment]
@amiour-billel do you mind sharing with which OS you have deployed our Docker image?

**Comment by amiour-billel** [comment]
@Paschalis yes of corse ,  i deployed the docker image in: 
**macOS Catalina V 10.15.4**
MacBook Pro (Retina, 15-inch, Mid 2015)
**CPU** 2,2 GHz Intel Core i7 quatre cœurs
**Memory** 16 Go 1600 MHz DDR3
**Graphic** Intel Iris Pro 1536 Mo

**Comment by Utopiah** [comment]
Had the same problem. Could be good to clarify on the main branch if it's unusable as-is and to switch to this branch instead, which worked for me.
