### ISSUE TITLE
Can't add floor plans

### ISSUE THREAD

**Issue by sbonzo** [dmsl/anyplace#351]
Hi everyone, I have builded my own server using the sbt console on http://localhost:9000, when I upload the floor plan I have this error despite the pop up say was successfully uploaded:

API: /anyplace/mapping/floor/uploadWithZoom
{“message”:“Cannot save floor plan on the server!“,”status_code”:400,“status”:“error”}

After refreshing the page, the floor plan addedd can't be viewed with this error:

/anyplace/floorplans64/building_bc9ab43-8cdf-41fb-a22c-fdf22d3fd767_1601891039813/1
{“message”:“Requested floor plan does not exist or cannot be read! (1)“,”status_code”:400,“status”:“error”}

I noticed that inside /anyplace-4.0/floor_plans/building_bc9ab43-8cdf-41fb-a22c-fdf22d3fd767_1601891039813 (auto created folder) there are two folder fl_0 and fl_1 with nothing inside.

They look like the folders where the floor pan should be loaded. 
I tried also with redirect my server on https://localhost with ssl certificate but I've still the same errors.

Can you please help me resolve this issue?

I've seen that many users have the same issue but why nobody answer to us?

Thanks in advance

**Comment by sbonzo** [comment]
Found solution.

**Comment by Soneliem** [comment]
@sbonzo 2 years later but do you remember how you solved your issue? We have exactly the same issue with the empty floor folders.
