### ISSUE TITLE
My building suddelnly removed from Archetiect 

### ISSUE THREAD

**Issue by GoldenWings** [dmsl/anyplace#37]
I've uploaded our building maps along with the RSS map and it was working perfectly, Except that i had one issue which is the floors of the building were not in the right order, we have four floors basement, ground, first floor and second floor i've ordered them respectively from 0 to 3 instead of -1 to 2 so i requested to edit the floor numbers via an email i've sent to you guys.
Now i can't find my building at all.
buid=building_cc6c953a-9ded-42fb-8c1f-6c697f670fcc_1464986495304
Any thoughts how and why it was removed ?

**Comment by kgeorgiou** [comment]
Hello again @GoldenWings, I am currently looking into it.

**Comment by kgeorgiou** [comment]
@GoldenWings It should be visible now. 
About the change of floor numbers in your building, I am still trying to find the best way to do it. 

Cheers.

**Comment by GoldenWings** [comment]
@kgeorgiou 
I confirm that the building is visible and good luck with the floors.

Thanks.
