### ISSUE TITLE
Floor map is not loading in tracker and logger

### ISSUE THREAD

**Issue by shashankkarkare** [dmsl/anyplace#38]
I have create new building and followed all the required steps to create floor and POIs. I am not able to see floor map in the tracker. I can only see POIs but no floor map. Logger is also not showing floor map. I am not able to create radio map as I cannot see floor map. 

I used this app earlier. I am facing this issue since last week when anyplace went from normal http to https.

Please help. 

Thanks,
Shashank

**Comment by Gattaco** [comment]
Hi I am in the same situation, I created a new building next to mine and there is no way that you can see the map in the mobile app, I changed even be mobile but still the same if they give us any solution.

**Comment by shashankkarkare** [comment]
Is anybody looking into this? Please provide any work around if available.

**Comment by kgeorgiou** [comment]
Hello @shashankkarkare & @Gattaco, 

Can you please tell me the building ID(s) of you building(s) so I can check them one by one?

There seems to be a temporary misconfiguration on the server, I will let you know once it's fixed.

Thanks.

**Comment by shashankkarkare** [comment]
Building ID is RushiBuild

Thanks,

**Comment by kgeorgiou** [comment]
@shashankkarkare your building "RushiBuild" should be loading correctly now. 

You might need to invoke the "Delete cached floor plans" option from the _preferences_ menu first.

Let me know if you have any trouble.

**Comment by shashankkarkare** [comment]
Hello,
Floor map is loaded correctly now. 
Thanks kgeorgiou for your assistance.
