### ISSUE TITLE
Anyplace PFM Jaén Spain

### ISSUE THREAD

**Issue by Gattaco** [dmsl/anyplace#39]
Hello my name is July'm a student at the University of Jaen in Spain.
The reason for the consultation is that my Master's Thesis will try positioning Inside and your application is one of those chosen for the job. I'm having some problems with it and do not really know what may be the reasons. I have two buildings of my university introduced with the plans of all plants, one called A3 (Building Engineering) as Enter some time in the practices of LBS subject, which if it appears perfectly but the second called A4 (Aulario Cesáreo Rodriguez Aguilera) can not get the planes appear in the mobile application to make the appropriate start wifi recorder. Any solution.
Thank you.

**Comment by kgeorgiou** [comment]
Hello July, the floor plan images seem to load correctly on the Web Viewer, which is good. 

I am looking into the issue with the Android app right now, I will let you know as soon as I have updates.

**Comment by kgeorgiou** [comment]
Hello again July, can you check now? (You might need to clear the floor plan cache.)

I believe the issue is resolved now for building "A4", but please let me know if there are still any problems.

**Comment by Gattaco** [comment]
Hello. I have performed the steps in AnyPlace Logger Preferences, Refresh Building and effectively as I load the A4 building, thanks thank you very much for your help.
