### ISSUE TITLE
Where is the Wi-Fi RSSI Vector that you use in the Sensor Fusion Algorithm?

### ISSUE THREAD

**Issue by heisenberg1995** [dmsl/anyplace#40]
I was trying to modify the RSSI vector slightly. Can you point out from where can it be accessed in the code? I understand that this vector(Wi-Fi RSSI vector) is finally put into the Sensor fusion functionality.

**Comment by constambeys** [comment]
Check AnyplaceTracker SimpleWifiReceiver class which receives the Wifi Scan results
