### ISSUE TITLE
Architect

### ISSUE THREAD

**Issue by kerryconvery** [dmsl/anyplace#42]
HI
I can't seem to open the architect page, its just blank.  Is the service down? if so when do you expect it to be back up?

https://anyplace.cs.ucy.ac.cy/architect/

thanks

**Comment by Costantinos** [comment]
Hello,

Thanks for contacting us, it should be fine now. Please check and let us know of any problems.

Best Regards,
C.

**Comment by kerryconvery** [comment]
Its working now thanks
