### ISSUE TITLE
Can't get radio map

### ISSUE THREAD

**Issue by SladLee** [dmsl/anyplace#43]
Hello, I'm new to this, so forgive me if I'm asking a stupid question here.

Suddenly became unable to download the radio map for a building I'm working on.
Getting errors like "No peer certificate", or timeouts. Weird as I've been using it for a few months now.

**Comment by SladLee** [comment]
Just an update, I just grabbed the latest version and am able to download them again. Sorry for the inconvenience.
Sometimes, it still bugs out and gives me the same errors though, could this be because of slow connection?

**Comment by constambeys** [comment]
Hello SladLee, it was indeed a problem with radiomaps but now should be fixed. Regarding the errors are you talking about the Android App because i think no errors are displayed

**Comment by SladLee** [comment]
Yes, it was the Android app. Still randomly getting timeout and "No peer certificate" errors. 
The error messages are not actually displayed, since the progress bar shown while downloading the radio map suddenly just disappears. Then, I checked the debug messages, and found those errors.
Any idea on how to prevent, or at least reduce the chances of the "No peer certificate" error popping out?

**Comment by constambeys** [comment]
Do you experience the problem in all buildings?

**Comment by SladLee** [comment]
Yes, though most of the time, I get connecting to services taking too long. I think most of these errors can be attributed to my slow connection of barely only 1.0 Mbps

**Comment by SladLee** [comment]
Ok, it's suddenly happening again. Not sure what's causing it.

**Comment by constambeys** [comment]
Hello SladLee, regarding the network problem I am suggesting to look at the Network Utils class.  Try to use a different library for the network functionality might solve the problem. I have read that Apache HTTP Client  is no longer recommended

**Comment by SladLee** [comment]
Will be trying to do just that then. Thanks for the suggestion. Will update if there's any progress.

**Comment by SladLee** [comment]
After changing from Apache HTTP to HttpUrlConnection, the problem seems to be gone entirely. Though, the JSON message response seems to be acting up. Will keep working on it.

**Comment by SladLee** [comment]
As far as my work has gone, most of the connection problems are gone. but suddenly, I'm getting the message "Floor selector has encountered an error". Any ideas?

**Comment by constambeys** [comment]
OK that is interesting. We should update to HttpUrlConnection then. 
The Floor selector is for automatically detecting at what floor is the user. Check Algo1Server because it makes an http post request to the server

**Comment by SladLee** [comment]
Should I post my code here? No guarantees though. And thanks for the tip, will look into that.

**Comment by constambeys** [comment]
Yes good idea

**Comment by SladLee** [comment]
Here it is. Just tell me if there's anything wrong with it.

`// <HTTP Post Json> (InputStream)
    private static InputStream ISdownloadHttpClientJsonPostHelp(String url, String json, int timeout) throws URISyntaxException, IOException {
        InputStream is;

        URL obj = new URL(url);
        HttpsURLConnection con = (HttpsURLConnection) obj.openConnection();
//		try {
            con.setConnectTimeout(timeout);
            con.setRequestMethod("POST");
            con.setRequestProperty("Accept", "application/json");
            con.setRequestProperty("Content-type", "application/json");
            con.setDoOutput(true);
            con.setDoInput(true);
            con.connect();

            OutputStream os = con.getOutputStream();
            BufferedWriter writer = new BufferedWriter(new OutputStreamWriter(os));
            writer.write(json);
            writer.flush();
            writer.close();
            os.close();

            int response = con.getResponseCode();
            if (response == HttpsURLConnection.HTTP_OK){
                is = con.getInputStream();
            }
            else {
                throw new RuntimeException("Service Error: " + con.getResponseMessage());
            }

            return is;
//		}
//        finally {
//            con.disconnect();
//		}

    }
`

**Comment by constambeys** [comment]
Thank you very much. I have updated the github and the playstore.

**Comment by SladLee** [comment]
Are you sure this can be used right away? I have a feeling since I never called HttpUrlConnection.disconnect(), there may be problems.

**Comment by constambeys** [comment]
I don't know about disconnect but to avoid memory leak you should close the input and output stream

**Comment by SladLee** [comment]
Ok, after updating the code, suddenly the "Floor selector has encountered an error" message never appeared again. Thank you very much for all the help you have given me. You can consider this issue closed now.

P.S. 
readInputStream function should include the line `stream.close()` to avoid memory leak as you've mentioned?
