### ISSUE TITLE
Using the code in other apps

### ISSUE THREAD

**Issue by kerryconvery** [dmsl/anyplace#44]
I'm sure this has been asked before but currently all of the functionality appears, although in distinct classes, seem to be tightly coupled to the app.  In the future will this be separated out in to libraries that can be used to make other apps?

**Comment by anyplaceucy** [comment]
How if you help us out on this?

**Comment by kerryconvery** [comment]
I don't yet understand the API well enough yet to take on such work but that is slowly changing as I continue to used the API.   At first I created a new project and tried to only bring in the navigation classes that I wanted to use but it started to feel like a bit of a rabbit hole as i found myself looking around for missing dependencies and resolving compiler errors etc.  Admittedly this was the first time I had really started to dig into the api and my java knowledge is limited so I may have just been going about it the wrong way.  The reason I only wanted the only the navigational stuff is that building the whole app exceeds the 64k limit and then I can't compile it for my older device which isn't a major issue but it got me thinking about splitting it up.

I guess I would start by separating navigation and logging into their own jar files and remove the activities as people might want to create their own UI.  For logging, like the app I am creating, you can use the existing Anyplace app to map an area and then build a custom app around only the navigation aspects.

But like I said, this might be totally wrong and I don't yet have enough experience with the Anyplace API to take this on.

**Comment by SladLee** [comment]
Actually, this is what I've been doing for the past few months. Turned most of the code into a library to be used in my app.

**Comment by kerryconvery** [comment]
That's awesome.  Is it available on git somewhere? My java experience is still rather limited I mostly work with C# and Delphi but I had seen libraries written as .jar so thought that was the way its done in java.  If you haven't made jar's how have you done it?

**Comment by SladLee** [comment]
I did not put it up as a github project, since this is actually my final year project for my current course. What I've done, however, is compile it as a separate project, in the lib folder of my application.

**Comment by kerryconvery** [comment]
I see, thats intresting.  I was actully thinking to split it up so that you
don't have to include the logger or other components you dont need, not
sure how modular it can be made. For example you can use the existing
anyplace app to create the heatmaps, etc and distrobute your own app which
only does navigation.  Or you might want to include the logger but provide
your own building creation and selection implementation. To be honest
though these might be edge cases. My own app for example takes the existing
app and adds new screens but i dont need the logger because i will be going
out and doing the setup for each site. I also dont need the building
selection because each site should only be able to see their own building
so i store the bldid in a db.

**Comment by SladLee** [comment]
Technically you can just delete whatever class you don't need once you manage to do what I did. Though progress has been quite slow, since I've been getting quite a lot of errors trying to load my building, like being unable to connect to anyplace service, connection timeout, no peer certificate, etc. Do you have any suggestions to avoid these?

**Comment by kerryconvery** [comment]
Sorry but i havent had such errors but if i do get them and discover a
resolution then i'll be sure to post it here.  In the meantime i'd suggest
you check that your internet connection is stable and that the anyplace
servers are available and reachable from your location.

**Comment by SladLee** [comment]
Unfortunately, I'm stuck with unstable connection the whole time here, so I will try to find a way around it.

**Comment by kerryconvery** [comment]
yeah sorry but can't really help with that. Perhaps someone else can
suggest something.
