### ISSUE TITLE
Mapping a single room

### ISSUE THREAD

**Issue by kerryconvery** [dmsl/anyplace#46]
Hi
I'm trying to map out a single room.  The room is 5x4.5m and has three wifi points within it.  
I'm not sure how I am to go about mapping it.  I've tried walking to all four corners and updating my position at each corner and I've also just tried walking around and around without updating my position.

Both times I collected about 20 readings.  However when I try to navigate the point barely moves and also when I'm at the starting point, i.e. the room entrance the point on the map is about 3m away.

I'm guessing that the room is too small and also that I don't have enough wifi points.  Would this be correct? If so what it the minimum room size and what would be the minimum number of wifi points required? 

Thanks

**Comment by kgeorgiou** [comment]
Hi @kerryconvery, your guesses are correct.

Generally, great accuracy can be achieved with: 
- Gathering a lot of readings.
- Covering as much possible area when gathering readings.
- The presence of high number of WiFi access points. (I'd say 3 is the bare minimum.)

However, keep in mind that for the time being, Anyplace is accurate up to **1.96m**. That radius almost covers the whole area of the room you described, so it's expected for the localization pin to not move much.

You can read more on how the 1.96m accuracy was achieved [here](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/lymberopoulos_MC2R_2014.pdf).

**Comment by kerryconvery** [comment]
Yes I thought that the small size of the room was the cause for the point not moving much.
Yesterday I mapped a large room at my place of work were there are lots of wifi points, this includes wifi routers, Sony TVs with wifi capability, etc, and the system worked as expected the first time.

**Comment by kgeorgiou** [comment]
Good to hear @kerryconvery, thanks for sharing! We are always keen on looking at different use cases and setups.

**Comment by kerryconvery** [comment]
Yeah so what I did was walk from the entrance of the room to each corner
and updated my position each time I turned to face the next corner.  I did
this until I was back at the start.  Is this the right way to map a single
room or can I just walk around randomly within the room without updating my
position? which do you think would work better?


Thanks.

**Comment by anyplaceucy** [comment]
Please check out the tutorial under Wiki
