### ISSUE TITLE
Custom Wifi beacons

### ISSUE THREAD

**Issue by kerryconvery** [dmsl/anyplace#48]
Hi.

Sorry for all of the questions.  

For our hack day project we are going to be using the Anyplace API in a warehouse environment to help simplify stock movement where each stock bin will be a POI.

We are building custom wifi beacons to work with the Anyplace API with the goal of improving accuracy.  What do you think would improve accuracy mostly?  a stronger signal, a directional antenna or a more stable signal, i.e. one that doesn't fluctuate much?  Anything other beacon qualities you can suggest that will improve the API accuracy would be helpful.  At this stage I don't know how much as can achieve but we want to give this a good try.

We have complete freedom as to where the beacons will be placed and how many.  So we'll be placing them in a such a way as to maximize line of sight and minimize obstructions.  The environment in which are will be placed is unlikely to change, although the odd forklift might be driving around from time to time.

**Comment by anyplaceucy** [comment]
That is a good idea! Please consider contributing your developments back to the Anyplace community.
