### ISSUE TITLE
How to load server code and run on local computer

### ISSUE THREAD

**Issue by harshitlalpura** [dmsl/anyplace#49]
Hello,

You have uploaded server code in development branch of this git. Can you please guide me what are the steps to run that code locally. Waiting for the reply.

Thanks.

**Comment by anyplaceucy** [comment]
A README file is currently under development. Please stay tuned.

**Comment by willjk** [comment]
I know this question is only 2 weeks old but is there a timeline for this being finished? I noticed in the dev branch we have some hard coded `http://anyplace.cs.ucy.ac.cy` in the front end

**Comment by anyplaceucy** [comment]
Please use the below until the views are fully documented.

https://github.com/dmsl/anyplace/blob/develop/ddocs.json

**Comment by akpmp** [comment]
how to install anyplace server in own computer

**Comment by akpmp** [comment]
how to solve Cross-Origin Request Blocked on anyplace server

**Comment by git1988** [comment]
I am also facing issue in running server code(architect,viewer) in localhost, I am using MAC but i have seen video for windows machine. Please help me

**Comment by arunravimv** [comment]
Issue while restoring couchbase views.

`cbrestore /home/couchsrv/anyplacedata http://anyplace:admin@localhost:8091 -x design_doc_only=1 -b anyplace -B anyplace`
>transfer design doc only. bucket msgs will be skipped.
>done

I guess my import is incomplete.
I am getting following Error.

> Cannot invoke the action, eventually got an error: com.couchbase.client.protocol.views.InvalidViewException: Could not load view "building_all" for design doc "nav"

**Comment by anyplaceucy** [comment]
Fixed in Anyplace v3. For more check the github page: https://github.com/dmsl/anyplace
