### ISSUE TITLE
Couchbase view required for starting Anyplace server

### ISSUE THREAD

**Issue by cmdr2** [dmsl/anyplace#54]
Hi,

I'm opening this issue more for tracking, not for pushing :-) 

I tried setting up the Anyplace server, and it needed the couchbase views that you mentioned in #34 . I'd love to play around with any test versions of it, in order to get the server running.

Thanks
~cmdr2

**Comment by anyplaceucy** [comment]
Please use the below until the views are fully documented.

https://github.com/dmsl/anyplace/blob/develop/ddocs.json
