### ISSUE TITLE
Incorrect data in Json Export

### ISSUE THREAD

**Issue by kerryconvery** [dmsl/anyplace#55]
Hi Guys

I've exported the POI json data via the architect application but the vales I'm getting back seem wrong.  That is, for every poi the coordinates_lat and coordinates_lon fields have the same value, and also is_building_entrance is true for all for all of them even though I have only one entrance. I've attached a copy of the json file.  I haven't yet checked what data comes back from the 

[poi_json.txt](https://github.com/dmsl/anyplace/files/386958/poi_json.txt)

When I query the endpoint, https://anyplace.rayzit.com/anyplace/navigation/pois/id, the is_building_entrance field is set correctly but the lat and lon values still seem incorrect.  Below are the results from the endpoint for two poi's at opposite ends of the room.

{
    "is_building_entrance": "false",
    "floor_number": "0",
    "pois_type": "Other",
    "buid": "building_9e72ac9e-4c08-4e4b-adc3-ee5024b64546_1468267872508",
    "image": "url_to_pois_image",
    "coordinates_lon": "174.7632873058319",
    "url": "-",
    "coordinates_lat": "-36.87109769062899",
    "floor_name": "0",
    "description": "-",
    "name": "Test POI",
    "is_door": "false",
    "is_published": "true",
    "puid": "poi_6b27388b-5fa3-403f-a9d4-dcf4345ad00d",
    "geometry": {
        "coordinates": [
            -36.87109769062899,
            174.7632873058319
        ],
        "type": "Point"
    },
    "status": "success",
    "message": "Successfully fetched Poi information!",
    "status_code": 200
}

{
    "is_building_entrance": "false",
    "floor_number": "0",
    "pois_type": "Other",
    "buid": "building_9e72ac9e-4c08-4e4b-adc3-ee5024b64546_1468267872508",
    "image": "url_to_pois_image",
    "coordinates_lon": "174.763351008296",
    "url": "-",
    "coordinates_lat": "-36.87101937131593",
    "floor_name": "0",
    "description": "-",
    "name": "czxczxc",
    "is_door": "false",
    "is_published": "true",
    "puid": "poi_06aeb79b-56a1-4337-a22a-0eba58df424d",
    "geometry": {
        "coordinates": [
            -36.87101937131593,
            174.763351008296
        ],
        "type": "Point"
    },
    "status": "success",
    "message": "Successfully fetched Poi information!",
    "status_code": 200
}

Thanks

**Comment by dvaler01** [comment]
I will check this issue asap ! Thank you for the feedback !!

**Comment by anyplaceucy** [comment]
Fixed in 2.8
