### ISSUE TITLE
User location changing continuously

### ISSUE THREAD

**Issue by shashankkarkare** [dmsl/anyplace#59]
Hi Team,

We are experiencing accuracy issue in localization in our building. User location is continuously changing.  We talked to our IT infrastructure team to check if there are any wireless access point issues. We came to know that access points in our building have variable strength. Its signal strength changes based on number of users connected. 

Is the variable strength causing accuracy issues? Do we need fixed signal strength access points for better accuracy?

Thanks,
Shashank

**Comment by anyplaceucy** [comment]
Read this: https://github.com/dmsl/anyplace/wiki/Best-Practices-for-producing-WiFi-Radiomap-In-Anyplace-Android-by-Christos-Laoudias
