### ISSUE TITLE
Web

### ISSUE THREAD

**Issue by jainvinitjain** [dmsl/anyplace#62]
anyplace API working with localhost:8080 fine but after deployment my side It is not working with my IP address 192.168.4.102:8080 always come error no matching building found. Please solve my Issue.

**Comment by dvaler01** [comment]
i work on localhost:9000 so give it a shot :)

**Comment by jainvinitjain** [comment]
I used localhost:9000 it work only own PC but I want to access my application from other PC So I used IP of my PC For Example 192.168.4.102:9000 but given same error no matching building found.

**Comment by westlakem** [comment]
Why was this closed? was it ever resolved?
