### ISSUE TITLE
 Windows Phone App does not show the mapping.

### ISSUE THREAD

**Issue by Gattaco** [dmsl/anyplace#64]
Hi recently acquired a Windows phone seeing that exists on the web the application for this platform but I have a problem and it does not show me the drawings uploaded buildings, particularly buildings are A4 and A3 of the University of Jaen Spain.

**Comment by panagorn** [comment]
I will check it

**Comment by panagorn** [comment]
What Windows version do you use?

**Comment by Gattaco** [comment]
Windows phone version is 10

**Comment by Gattaco** [comment]
If something sirbe the phone it is a Nokia Lumia 930

**Comment by Gattaco** [comment]
any solution

**Comment by panagorn** [comment]
It's a problem of windows 10. They don't allow load tiles from storage. So there is no solution yet.

**Comment by Gattaco** [comment]
It is seen that these windows are not very thin with its mobile operating system, anyway've already got an Android phone and continue with the to do my project. Thank you anyway.

**Comment by Gattaco** [comment]
Hello I installed Windows Phone 8.1 Demian and planes are loaded and works well, I believe that the application is not updated to the Windows Phone platform 10 that did not work properly. I think I can after the application using both Android and Windows Phone to say that I prefer the Android, I see it better for use than Windows so that seeketh me an Android to continue the work.
Greetings.
