### ISSUE TITLE
I need couchbase views

### ISSUE THREAD

**Issue by harshitlalpura** [dmsl/anyplace#69]
Hello,

I need to setup couchbase views. Please send me couchbase views. Please help me.

Thanks

**Comment by mihaildemidoff** [comment]
Hello,

I am also waiting for couchbase views. 
There are several issues with this question #54 #49

**Comment by anyplaceucy** [comment]
Please use the below until the views are fully documented.

https://github.com/dmsl/anyplace/blob/develop/ddocs.json

**Comment by harshitlalpura** [comment]
Can you please tell me the process to restore this views ? ?
