### ISSUE TITLE
Architect failure

### ISSUE THREAD

**Issue by Gattaco** [dmsl/anyplace#71]
Hi I was working on my building A3 at the University of Jaen and there has been a failure because I no longer appears in the Architect mode, the display mode if this any solution

**Comment by Gattaco** [comment]
Please someone who can help me, because I can not access my building A3 thanks

**Comment by anyplaceucy** [comment]
Your issue is being investigated

**Comment by Gattaco** [comment]
hello any solution to the problem with the architect, right now I have my job to Master stopped because of this problem with my building some solution A3 from the University of Jaen. Thank you.

**Comment by Costantinos** [comment]
Hello,

We have checked the building and everything seems ok on the architect. Can you please provide me more info about the issue (e.g what browser are using)?

Thank you,
C.

**Comment by Gattaco** [comment]
Hello good evening, my problem arose when I was working in my building A3,
suddenly page was left hanging cool and the building and I went out, I
tested with several browsers and different computers but I have not gotten
me coming back. I attach a screenshot of the situation in which I find
myself. I am the architect and want to select one of my two buildings but
only I get the A4 A3 did not appear.

2016-10-13 21:33 GMT+02:00 Costantinos Costa <notifications@github.com>:

**Comment by Gattaco** [comment]
Hello any solution to the problem, not I can do but I need to access the
edifio is an important part of TFM and I need terminnarlo. Greetings.

2016-10-13 22:11 GMT+02:00 Life of Gattaco <gattacajlr@gmail.com>:

**Comment by Gattaco** [comment]
Hi good morning, some solution to the problem, I still can not finish my edifio A3 of the University of Jaen, I need to access it to finish the architect and continue to master project. Greetings.

**Comment by anyplaceucy** [comment]
Dear users, we are looking into the problem. Please be patient. 

Meanwhile, please backup your buildings in Architect and if time is pushing consider running your own Anyplace service (full sources available in Github).

All the best
The Anyplace Team

**Comment by anyplaceucy** [comment]
Gattaco, 

The A3 building is not deleted (we can see it) but haven't identified the reason why it doesn't appear in your Architect. We are looking at it. 

![pastedgraphic-2](https://cloud.githubusercontent.com/assets/19922199/19430072/1a53d66e-9453-11e6-9d5a-6a6999c24fee.jpg)

All the best
The Anyplace Team

**Comment by Gattaco** [comment]
Hi good morning, I entered back into my account and I see that still did
not solve the problem, I can not wait much more time passed and I have to
go over things. I thought that if it is not possible to re-enter the
building A3 this is deleted and build it again, this would be more work for
me but at least I could do something and finish it. regards

2016-10-17 10:19 GMT+02:00 Anyplace <notifications@github.com>:

**Comment by anyplaceucy** [comment]
Gattaco,

We still haven't identified the cause of your problem. The A3 building is online as you can observe through the following URL:

https://anyplace.cs.ucy.ac.cy/viewer/?buid=building_e8d2d080-e08b-4f60-bc5b-9f1eda6d0a19_1454482748642

In any case, if you want to move on and create a new building, its useful to utilize the A3 Model, containing POIs, images, etc as these have been exported through the architect. Follow the below link which will be active for a while:

https://www.dropbox.com/s/894u08b1r6h6qmw/building_e8d2d080-e08b-4f60-bc5b-9f1eda6d0a19_1454482748642.zip?dl=0

The Anyplace Team

PS: You might consider organizing all buildings of your project in a "CAMPUS" (that is the latest feature available through the Architect). An example campus is the following: https://anyplace.cs.ucy.ac.cy/viewer/?cuid=ucy

**Comment by Gattaco** [comment]
Hello good afternoon:
I've been talking to my guardian end Master work on this issue and has contacted you to solicitaros that agreguéis me as a collaborator of my building the A3 Building Engineering and Technology in order to have access to it. This is a possible solution to me is also valid.

**Comment by kgeorgiou** [comment]
@Gattaco, can you please share the link to the Google+ profile you use to sign in? (e.g. https://plus.google.com/u/0/+KyriakosGeorgiouCy) 

I can then check if that profile has the correct access permissions for the building, otherwise I'll adjust them accordingly.

(You can post the link to the Google+ profile here or send it through at the email address I have listed on my Github profile.)

Thanks.

**Comment by kgeorgiou** [comment]
@Gattaco, I've made a change, can you see it now?

**Comment by Gattaco** [comment]
Yes I can see It now

**Comment by jlbalboa** [comment]
Many thanks @kgeorgiou and @anyplaceucy 
I can see the buildings in Architect too. 
Regards.

**Comment by akpmp** [comment]
Hi Good Evening,
i have run anyplace server on own server. after adding new building  then given  error like 
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:9000/anyplace/mapping/accounts/sign. (Reason: CORS header 'Access-Control-Allow-Origin' missing
How to resolve this issues
Thank

**Comment by anyplaceucy** [comment]
Its nice to see the mapping online:

youtu.be/8m-C2fx8prM
youtu.be/G2OeqT8Prn0
youtu.be/44gFZSEXq1o
youtu.be/ENSBpiDeGKI

Well done!

PS: @akpmp  please reopen a new thread if the problem persists.
