### ISSUE TITLE
cannot add a building from architect

### ISSUE THREAD

**Issue by ZeeshanMohammad** [dmsl/anyplace#72]
Hi !
 i have downloaded the current git repo of architect and followed the readme file and was able to run a server. I have logged in using the google account and it gives me unauthorized error when adding building.
I have searched for the error and looks like the error is because of the google api changed. Its mentioned in the anyplace main website that this issue is fixed in V2.8 . Is the new code checked in git?? i see there are no changes since 9 months  in the repo.

Is there a workaround in the current repo to use the architect module?

Thanks,
zeeshan

**Comment by anyplaceucy** [comment]
Its located under the develop branch: 

https://github.com/dmsl/anyplace/tree/develop

**Comment by Gattaco** [comment]
ZeeshanMohammad Hi, your problem is similar to mine in my case the architect has disappeared me one of my buildings, and I am a little stand with the theme of Master's Thesis. hopefully soon we have solved these problems thanks.

**Comment by anyplaceucy** [comment]
See https://github.com/dmsl/anyplace/issues/71
