### ISSUE TITLE
Logger showing standing when I a walking

### ISSUE THREAD

**Issue by lsushant** [dmsl/anyplace#73]
I am using logger for logging the data . When I click on start recording , I see that the status is standing . It should be walking . Am I missing some thing . Do I have to place Wifi routes  in the building .

I have uploaded the building plan in architect it is Manyata D4 . 

Please help
Sushant

**Comment by constambeys** [comment]
It should change automatically when you are moving. When you move the device does it change?

**Comment by lsushant** [comment]
Nope it does not change when I move the device . Is there a setting on the device to make it work.

Regards
Sushant

**Comment by constambeys** [comment]
Yes there is a walking sensitivity slider in settings. If you have a low value then it is constantly standing and if you have a high value constantly walking. Check if this is the case and try to find the optimal value
