### ISSUE TITLE
Which version of couchbase you are using ?

### ISSUE THREAD

**Issue by harshitlalpura** [dmsl/anyplace#74]
Hello.

 Please tell me which version of couchbase your are using. I am getting compatibility issues, Please help,.
Thanks.

**Comment by kgeorgiou** [comment]
Currently we are running the 2.1.1 community version.

**Comment by emptymatt** [comment]
In the main README.md it's written that Anyplace Couchbase 3.0 Version will be available in May 2017.
Now what about this project?

**Comment by anyplaceucy** [comment]
Alpha version is already internally tested. Please be patient for a few more days.
