### ISSUE TITLE
Problem with self hosted Architect Module..

### ISSUE THREAD

**Issue by ZeeshanMohammad** [dmsl/anyplace#76]
I am trying with the develop tag architect module.But still stuck with the same issue of unable to place buildings.i have followed the read me document and implemented in the same way it is. But still the same issue as anyplace master.Can u guys please help me with that.
![projmid](https://cloud.githubusercontent.com/assets/18724084/19650461/09c53a5a-99cf-11e6-8b37-35eb8c831376.PNG)

**Comment by kgeorgiou** [comment]
Hello @ZeeshanMohammad, have you managed to run the Anyplace [server](https://github.com/dmsl/anyplace/tree/develop/server) locally as well? 

Where does `AnyplaceAPI.FULL_SERVER`, in [scripts/AnyplaceAPI.js](https://github.com/dmsl/anyplace/blob/master/architect/scripts/AnyplaceAPI.js#L34), point to?

**Comment by ZeeshanMohammad** [comment]
Thank you George for responding.Yes i have them pointing them to my local server now but the problem is the same.Does it has anything to do with the json files?
Can u please help me with hosting the architect module in my local machine.
Thank you,

Regards,
Zeeshan Mohammad

**Comment by ManishChauhan000** [comment]
Hi @ZeeshanMohammad

as per your screenshot there is not showing building dropdown that may be reason you are facing this issue . for confirming please open browser console window check there will be some error like
 
![capturse](https://cloud.githubusercontent.com/assets/9263792/19927038/ffd9bbdc-a11d-11e6-9ad6-4163e0fef5a1.PNG)

if i am right the install below dependency using : 
bower install angular-ui-select

i hope this will resolve your issue

**Comment by ZeeshanMohammad** [comment]
Hey thank you for showing interest,I have tried installing angular using your command but it throws an error.I am attaching the screen shot of the error.I have tried installing angular using "bower install angular --force". Isnt this the right way to do
![angular problem](https://cloud.githubusercontent.com/assets/18724084/19934914/47a2149c-a0e6-11e6-9e37-d178e3cca9f2.JPG)

**Comment by ManishChauhan000** [comment]
Hey 

please find the below video like which will helpful for you :

http://sendvid.com/mzdx9xd7?secret=d68fd7ad-9408-4675-a751-743358de55fe

**Comment by ZeeshanMohammad** [comment]
Thanks a lot,Manish
That has help me in resolving the issue.
