### ISSUE TITLE
Android implementation 

### ISSUE THREAD

**Issue by siddartha915** [dmsl/anyplace#78]
Hi
Which files are we supposed to use to get the application running and what dependencies are needed

**Comment by ManishChauhan000** [comment]
Hi,
i think  you need the below dependencies :
Android stdio
gradle :  2.1.0
sdk platform : android 6.X

**Comment by praveenke6** [comment]
Hi,
   We tried running the android application using android studio. Gradle is build but i am having the following error;

Error:Execution failed for task ':Anyplace:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/LICENSE
  	File1: /Users/praveenemani/Desktop/anyplace-master/android/Anyplace/libs/apache-mime4j-core-0.7.2.jar
  	File2: /Users/praveenemani/Desktop/anyplace-master/android/Anyplace/libs/jackson-core-asl-1.9.11.jar

can anybody suggest a solution for this.

**Comment by ManishChauhan000** [comment]
Hi Praveen ,

watch this video this will help in resolving your issue  and project setup :
http://sendvid.com/5mn48mpw 

Thanks you
