### ISSUE TITLE
Sharing buildings or floors

### ISSUE THREAD

**Issue by jlbalboa** [dmsl/anyplace#8]
Hi,

I have one question about the buildings and floors uploaded to the architect.

Is it possible to share them by two or more users?
In my opinion this would be necessary in order to not to depend on only one person.
If this person stops working on an institution, the buildings and floors would need to be duplicated and all the work redone by any other person.

Thanks in advance!

**Comment by kgeorgiou** [comment]
Hello @jlbalboa,

You are absolutely right. 

We recognised the need to share the workload of mapping a building to multiple users when we were mapping our campus and running our crowdsourcing experiments. We have actually implemented the functionality for internal use, through our admin dashboard.

It should be easy to make the functionality public on the Architect soon. For the time being though, we can manually add additional members to your building(s). Just send an email with your request to anyplace@cs.ucy.ac.cy and the team will take care of it.

Cheers.

**Comment by jlbalboa** [comment]
Hello @kgeorgiou ,
Thank you very much for the quick response and for giving us the possibility to add additional members to the buildings of our campus (University of Jaén, Spain).
I'll follow your instructions and send that email.
Thank you again!
