### ISSUE TITLE
Viewer accessing private buildings via API key

### ISSUE THREAD

**Issue by willjk** [dmsl/anyplace#80]
Is there a way to get a viewer we host to access the anyplace hosted servers private buildings via an api key? Possibly getting a different token to authorize through URL?

**Comment by anyplaceucy** [comment]
Private buildings are just not displayed through the VIEWER. As such, you should be able to access them through the API without any additional keys. As a rule of thumb, you only need the API keys for  actions that aim to change content loaded on Anyplace by specific users.
