### ISSUE TITLE
Every time server throws NumberException 

### ISSUE THREAD

**Issue by harshitlalpura** [dmsl/anyplace#81]
I am running your server code on play framework 2.2.1 and Couchbase Version: 3.0.1 Community Edition (build-1444) but when i upload rss log file server throws Error while authenticating RSS log file /home/azureuser/server/radiomaps_frozen/b_fae08f67d3d8b648124df670f65176fa/7/indoor-radiomap-mean.txt: Line 3 For input string: "-54.8"
-54.8 is just an example.. mean file contains many float values 

Please help.

Thanks

**Comment by anyplaceucy** [comment]
Fixed in Anyplace v3. For more check the github page: https://github.com/dmsl/anyplace
