### ISSUE TITLE
Unable to import JSON in all cases 

### ISSUE THREAD

**Issue by adulli** [dmsl/anyplace#84]
hey guys amazing job , 

though i am having an issue importing a JSON file with POI's . even when i create a new one as a dummy and export it , then import it. it still says something went wrong. 

last time i tried to import them i changed all the overwrite to true. it still gave me a log file saying under each POI, "Something went wrong while updating POI"

could you please help me look into this if possible ?

**Comment by dvaler01** [comment]
can you upload a part of json in comments ?

**Comment by adulli** [comment]
so i upload this 

{
    "building": {
        "floors": [
            {
                "floor_number": "3",
                "pois": [
                    {
                        "name": "Mosque",
                        "description": "Mosque\nPrayer Area \nمصلى",
                        "puid": "poi_03b2b014-539b-46cc-b806-373a72bc0c8d",
                        "pois_type": "Mosque",
                        "coordinates_lat": "24.714283523812146",
                        "coordinates_lon": "46.671867817640305",
                        "overwrite": "true",
                        "is_building_entrance": "false"
                    },
                    {
                        "name": "Innovation Room",
                        "description": "Innovation Room",
                        "puid": "poi_03c5b714-7b70-4abf-80c6-ccdfe7110d74",
                        "pois_type": "Room",
                        "coordinates_lat": "24.71454179565398",
                        "coordinates_lon": "46.671608313918114",
                        "overwrite": "true",
                        "is_building_entrance": "false"
                    }
     ]
            }
        ],
        "buid": "building_7b252601-26a2-4001-9830-b22643105e41_1478506448500",
        "name": "Suhail building",
        "description": "-",
        "coordinates_lat": "24.7141275858369",
        "coordinates_lon": "46.672697961330414"
    }
}

and after that what i keep getting is this 


{
    "pois": [
        {
            "name": "Mosque",
            "puid": "poi_03b2b014-539b-46cc-b806-373a72bc0c8d",
            "description": "Mosque\nPrayer Area \nمصلى",
            "status": "Something went wrong while updating POI."
        },
        {
            "name": "Innovation Room",
            "puid": "poi_03c5b714-7b70-4abf-80c6-ccdfe7110d74",
            "description": "Innovation Room",
            "status": "Something went wrong while updating POI."
        }
   ]
}

1-of course please note that i just backed up the old point and removed the map then i wanted to put them back in on a much better image that i imported, could this be the reason ?

2-if so will i be able to upload them through the API's? as i have been trying to do that but was unsuccessful as i do not know the full link off adding any POI through the web services. for example the link for adding a POI is 
https://anyplace.cs.ucy.ac.cy/developers/3/buid/....
what would be the correct link to add them ? with the Oauth 2 through an external tool ?

**Comment by adulli** [comment]
it had been resolved i realized that the developer site has all the information including the link and the paths. Thanks :)
