### ISSUE TITLE
vierver page is rejecting the connection

### ISSUE THREAD

**Issue by carloswais** [dmsl/anyplace#85]
I am using the anyplace ( indoor mapping)  the one you developed I managed to upload the floor map  on the architect and gave them the coordinates. Now I am trying to loggin again to the viewer but im not able to see anything as the page is not loading. It says that the page is rejecting the connection for some reason.
>
> Woud you be able to help me? As I spent yesterday all day uploading the maps floors and giving them the coordinates to all the positions within the map.

**Comment by Costantinos** [comment]
Hello @carloswais , could you please try it now?

**Comment by carloswais** [comment]
yes all good Now. what was the matter?

**Comment by Costantinos** [comment]
Hello, we had a small network issue. Everything should be fine now.

**Comment by carloswais** [comment]
Hi there, do you know how can i integrate it with other softwares?

i am attempting to integrate it with servicenow do you think is possible?


carlos bello

**Comment by Costantinos** [comment]
Hello Carlos,

I believe that you can integrate Anyplace with servicenow due to high interoperability, which is offered by the Anyplace API.

Thanks,
Costantinos Costa

**Comment by carloswais** [comment]
Any chance you can guide us on this. i dont really understand the API from your page like i cant get the token and so on.
