### ISSUE TITLE
request to delete wifi samplings

### ISSUE THREAD

**Issue by navidfalla** [dmsl/anyplace#87]
Hi there,
I have been working on a building named Moss Arts Center in Blacksburg Virginia.
I did a round of wifi logging with a google tango tablet, and I think because of the special situation of the device it messed up with everything. So now I'm trying to use a new device to log the building, but the navigator always shows the direction of the device 90 degrees wrong...
Could you please delete the wifi loggings I have done so far, so I can start over? I couldn't find that option... I don't want to delete the floor plans, just the wifi logging.
My email is:
navidb[at]vt.edu
Thanks,
Navid

**Comment by navidfalla** [comment]
If you are able to delete by date, I would appreciate it if you delete everything that has done before 1/12/2016, the ones on 1/12/2016 have been done by a new device and should be fine.
If that's too hard, you can delete the whole wifi logging of the building.

**Comment by navidfalla** [comment]
Hi there,
I would really appreciate some help with this issue.
Thanks,
Navid

**Comment by navidfalla** [comment]
Hi there,
I'm sorry for sending too many posts, but our experiments has been stopped and we are waiting for this problem to solved to check if we can get a curacy from Anyplace and continue with it in our experiments.
Could you let me know asap if it's possible?
Thanks,
Navid

**Comment by anyplaceucy** [comment]
Is planned for tomorrow

**Comment by navidfalla** [comment]
Hi there,
Any news on this?

**Comment by anyplaceucy** [comment]
If not solved, please reopen.
