### ISSUE TITLE
I can not access my buildings

### ISSUE THREAD

**Issue by Gattaco** [dmsl/anyplace#92]
Hello good day
I currently do not have access to my buildings A3 and A4 of the University of Jaen in Spain, I need to access them as I have to update the cartography and finish my Master's Degree.
I would like to be able to access my buildings even if I am a collaborator.
Thank you.

**Comment by Gattaco** [comment]
Hello good day.

Some solution to my problem.

Thank you

**Comment by Gattaco** [comment]
Hi, I'm running out of time and I do not see a solution to my problem.
In the end I will have to access from my tutor's account of the Master's Project José Luis, but I do not think that is the solution.

Thanks for everything

**Comment by Costantinos** [comment]
Could you please try it now?

**Comment by Gattaco** [comment]
I can now access my building A3 but not the A4

**Comment by Gattaco** [comment]
Thanks for your help

**Comment by Gattaco** [comment]
This access is very old, my buildings are much more avamzados, my last access was a couple of weeks ago.

**Comment by Costantinos** [comment]
Hello, Do you mean that you have less POIS for your buildings?

**Comment by akpmp** [comment]
Hi I have login and add new building   then give error like Cross-Origin Request Blocked ho to solve it.

**Comment by anyplaceucy** [comment]
Please reopen if problem persists
