### ISSUE TITLE
Basic Funcionality

### ISSUE THREAD

**Issue by TSpaceM** [dmsl/anyplace#93]
Hi Folks,

This query is reposted as requested from the generic email address: anyplace@cs.ucy.ac.cy
>  
> I’m interested in the potential application of anyplace in a public hospital system for both wayfinding and object tracking.
> Is this an area suitable for Anyplace?  I’m not a developer or anything, so can I confirm what this does?  As I understand it, you can:
> ·         Upload one of several stacked floor plans
> ·         Walk around with the logger so it understands where you are in the building which relates multiple wifi base stations/distance to a floor plan
> ·         After mapping, people can be told where they are in the building based on the previous mapping.
> ·         WiFi devices in the building can know where they are based on the previous mapping
> Is this generally correct?
>  
> Thanks,
> T

**Comment by anyplaceucy** [comment]
Hi T,

You got everything right (all 4 bullets)!

However, object tracking is currently not available in Anyplace. For this you will need some type of Wi-Fi beacons (see http://www.aislelabs.com/reports/beacon-guide/) and hook them to the Anyplace service through the Anyplace API.

Industrial RTLS for the Healthcare sector, e.g., Ekahau, Aeroscout, Sanitag, etc. provide this functionality for a hefty price. If some basic development could be afforded (to integrate the beacon functionality), Anyplace is a great starting point.

The Anyplace Team

PS:  A good overview article about what Anyplace does and what other systems offer is available at the below URL: http://www.cs.ucy.ac.cy/~dzeina/papers/ic16-iin.pdf

A powerpoint presentation of the above PDF (in the form of a tutorial) is provided at the below URL:
http://www2.cs.ucy.ac.cy/~dzeina/talks/mdm15-seminar.pptx
