### ISSUE TITLE
Show navigation path across multiple floors (i.e. transparent for other floors)

### ISSUE THREAD

**Issue by JohannesBenzing** [dmsl/anyplace#95]
Is it possible for anyplace to show a navigation path across multiple floors like in following screenshot?
http://imgur.com/a/IxO8K
![mazemap_example](https://cloud.githubusercontent.com/assets/8440608/21424937/58153fe8-c846-11e6-8053-45455d541f0f.png)
This is screenshot is from the similiar commercial product mazemap.com

Thank you and best Regards,
Johannes Benzing

**Comment by anyplaceucy** [comment]
It actually does so already (both in Viewer and Navigators_!

The only thing to remember is that you need to connect 2 stairs on different floors with a connectors. This is something that can be carried out in Architect.

Anyplace Team

**Comment by JohannesBenzing** [comment]
I cannot get it to work.
Can you please link to an example building where it works?

**Comment by anyplaceucy** [comment]
Try: https://goo.gl/3X3334

You have to click on a POI, select the next floor level, click on the next POI and get the line connected.

**Comment by JohannesBenzing** [comment]
I only tested with Google Chrome.
![floor1](https://cloud.githubusercontent.com/assets/8440608/21425525/e9fd7652-c849-11e6-82db-4f8bcf4597aa.PNG)
![floor2](https://cloud.githubusercontent.com/assets/8440608/21425530/edf890a2-c849-11e6-97b5-4d28c11b9cef.PNG)

I think you misunderstood me. If look again at my first screenshot you can see a "normal" line AND a transparent dotted line(for the other floor). So you while viewing only one floor you can already see where you have to go on the other floor thanks to the transparent dotted line. Is it also possible with anyplace to display such a transparent dotted line.
