### ISSUE TITLE
Map Error

### ISSUE THREAD

**Issue by kodkafali** [dmsl/anyplace#99]
I am download release V2.8 . But map does not appear on screen. Could you help me this metter?
![maps](https://cloud.githubusercontent.com/assets/11686662/22021483/b328e532-dcce-11e6-8fea-97c0005e231a.jpg)

**Comment by constambeys** [comment]
You probably haven't specified the Google API key in manifest. Check google documentation how to generate the API key

https://developers.google.com/maps/documentation/android-api/signup

**Comment by kodkafali** [comment]
I am specified the Google API key in manifest file.
